"use client";

import { createContext, useContext, useState, useEffect, useMemo, useCallback, type ReactNode } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  tDesc: (key: string, fallback: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({ language: "en", setLanguage: () => {}, t: (k) => k, tDesc: (k, fb) => fb });

export function useLanguage() {
  return useContext(LanguageContext);
}

// Protected terms that should never be translated (game terminology)
const PROTECTED_TERMS = [
  // Spell names (common ones - will be expanded)
  "Fireball", "Magic Missile", "Cure Wounds", "Shield", "Mage Armor", "Detect Magic", "Identify",
  "Thunderwave", "Burning Hands", "Sleep", "Charm Person", "Command", "Healing Word",
  "Bless", "Bane", "Guiding Bolt", "Inflict Wounds", "Sanctuary", "Thaumaturgy",
  "Eldritch Blast", "Minor Illusion", "Prestidigitation", "Mage Hand", "Light",
  "Ray of Frost", "Acid Splash", "Poison Spray", "Shocking Grasp", "True Strike",
  "Vicious Mockery", "Spare the Dying", "Guidance", "Resistance", "Druidcraft",
  "Thorn Whip", "Produce Flame", "Shillelagh", "Mending", "Message", "Dancing Lights",
  "Friends", "Fire Bolt", "Ray of Sickness", "Witch Bolt", "Hellish Rebuke",
  "Armor of Agathys", "Expeditious Retreat", "False Life", "Feather Fall", "Find Familiar",
  "Fog Cloud", "Grease", "Jump", "Longstrider", "Protection from Evil and Good",
  "Thunderous Smite", "Wrathful Smite", "Absorb Elements", "Alarm", "Animal Friendship",
  "Beast Bond", "Charm Person", "Color Spray", "Comprehend Languages", "Detect Poison and Disease",
  "Disguise Self", "Dissonant Whispers", "Earth Tremor", "Entangle", "Expeditious Retreat",
  "Faerie Fire", "False Life", "Feather Fall", "Find Familiar", "Fog Cloud", "Goodberry",
  "Grease", "Healing Word", "Heroism", "Hideous Laughter", "Hunter's Mark", "Ice Knife",
  "Identify", "Illusory Script", "Jump", "Longstrider", "Mage Armor", "Magic Missile",
  "Protection from Evil and Good", "Purify Food and Drink", "Ray of Sickness", "Sanctuary",
  "Shield", "Shield of Faith", "Silent Image", "Sleep", "Speak with Animals", "Tasha's Hideous Laughter",
  "Thunderwave", "Unseen Servant", "Witch Bolt",
  // Class names
  "Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard", "Artificer",
  // Race names
  "Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Halfling", "Half-Orc", "Human", "Tiefling",
  "Aarakocra", "Genasi", "Goliath", "Kenku", "Tabaxi", "Triton", "Bugbear", "Goblin", "Hobgoblin", "Kobold", "Orc", "Yuan-ti Pureblood",
  "Feral Tiefling", "Aasimar", "Firbolg", "Kalashtar", "Shifter", "Warforged", "Changeling", "Eladrin", "Sea Elf", "Shadar-kai",
  "High Elf", "Wood Elf", "Dark Elf", "Drow", "Hill Dwarf", "Mountain Dwarf", "Lightfoot Halfling", "Stout Halfling", "Rock Gnome", "Forest Gnome",
  // Damage types
  "Acid", "Bludgeoning", "Cold", "Fire", "Force", "Lightning", "Necrotic", "Piercing", "Poison", "Psychic", "Radiant", "Slashing", "Thunder",
  // Spell schools
  "Abjuration", "Conjuration", "Divination", "Enchantment", "Evocation", "Illusion", "Necromancy", "Transmutation",
  // Conditions
  "Blinded", "Charmed", "Deafened", "Frightened", "Grappled", "Incapacitated", "Invisible", "Paralyzed", "Petrified", "Poisoned", "Prone", "Restrained", "Stunned", "Unconscious", "Exhaustion",
  // Ability scores
  "Strength", "Dexterity", "Constitution", "Intelligence", "Wisdom", "Charisma",
  // Skills
  "Acrobatics", "Animal Handling", "Arcana", "Athletics", "Deception", "History", "Insight", "Intimidation", "Investigation", "Medicine", "Nature", "Perception", "Performance", "Persuasion", "Religion", "Sleight of Hand", "Stealth", "Survival",
  // Alignments
  "Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "True Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil",
  // Common D&D terms
  "Action", "Bonus Action", "Reaction", "Concentration", "Ritual", "Cantrip", "Spell Slot", "Hit Points", "Armor Class", "Saving Throw", "Proficiency Bonus", "Advantage", "Disadvantage", "Critical Hit", "Initiative", "Speed", "Hit Dice", "Death Save", "Long Rest", "Short Rest", "Level Up", "Experience Points",
  // Subclass terms
  "Subclass", "Archetype", "Circle", "Domain", "Oath", "Patron", "Tradition", "College", "Path", "Way",
  // Equipment
  "Weapon", "Armor", "Shield", "Potion", "Scroll", "Wand", "Staff", "Rod", "Ring", "Amulet", "Cloak", "Boots", "Gloves", "Belt", "Helmet", "Gauntlets",
  // Currency
  "Copper", "Silver", "Electrum", "Gold", "Platinum",
  // Features
  "Darkvision", "Fey Ancestry", "Trance", "Relentless Endurance", "Savage Attacks", "Menacing", "Hellish Resistance", "Infernal Legacy",
  "Brave", "Lucky", "Halfling Nimbleness", "Naturally Stealthy", "Stout Resilience", "Dwarven Resilience", "Dwarven Combat Training", "Tool Proficiency", "Stonecutting",
  "Skill Versatility", "Fey Ancestry", "Trance", "Keen Senses", "Fey Step", "Mask of the Wild", "Elf Weapon Training", "Cantrip", "Extra Language",
  "Gnome Cunning", "Artificer's Lore", "Tinker", "Speed", "Size", "Languages",
  // Common spell mechanics
  "Dexterity", "Constitution", "Wisdom", "Intelligence", "Charisma", "Strength",
  "Melee", "Ranged", "Touch", "Self", "Area", "Sphere", "Cube", "Cone", "Line", "Cylinder",
  "Instantaneous", "Round", "Minute", "Hour", "Day", "Until Dispelled", "Until Dispelled or Triggered",
  "Verbal", "Somatic", "Material",
  "Constitution Save", "Dexterity Save", "Wisdom Save", "Strength Save", "Intelligence Save", "Charisma Save",
  "Melee Spell Attack", "Ranged Spell Attack",
  "Higher Level", "Upcast", "At Higher Levels",
];

const protectedTermsRegex = new RegExp(`\\b(${PROTECTED_TERMS.map(t => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`, 'gi');

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "DND Wizard",
    "nav.home": "Home",
    "nav.new": "New",
    "nav.myCharacters": "My Characters",
    "common.back": "Back",
    "common.next": "Next",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.apply": "Apply",
    "common.close": "Close",
    "common.edit": "Edit",
    "common.view": "View",
    "common.delete": "Delete",
    "common.remove": "Remove",
    "common.add": "Add",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.gotIt": "Got it",
    "theme.toggle.light": "Switch to light mode",
    "theme.toggle.dark": "Switch to dark mode",
    "description.show": "Show descriptions",
    "description.hide": "Hide descriptions",
    "character.identity": "Identity",
    "character.race": "Race",
    "character.class": "Class",
    "character.abilityScores": "Ability Scores",
    "character.background": "Background",
    "character.skills": "Skills",
    "character.equipment": "Equipment",
    "character.spells": "Spells",
    "character.subclass": "Subclass",
    "character.finalTouches": "Final Touches",
    "character.level": "Level",
    "character.xp": "Experience Points",
    "character.hp": "Hit Points",
    "character.currentHp": "Current HP",
    "character.maxHp": "Max HP",
    "character.tempHp": "Temp HP",
    "character.speed": "Speed",
    "character.proficiency": "Proficiency Bonus",
    "character.inventory": "Inventory",
    "character.currency": "Currency",
    "character.spellcasting": "Spellcasting",
    "character.features": "Features",
    "character.traits": "Traits",
    "character.languages": "Languages",
    "character.deathSaves": "Death Saves",
    "character.stable": "Stable",
    "character.dead": "Dead",
    "status.dead": "Dead",
    "character.success": "Success",
    "character.failure": "Failure",
    "character.attacks": "Attacks",
    "character.noAttacks": "No attacks configured",
    "character.sheet": "Character Sheet",
    "character.returnHome": "Return Home",
    "character.editMode": "Edit Mode",
    "character.actions": "Actions",
    "character.heal": "Heal",
    "character.damage": "Damage",
    "button.takeDamage": "Take Damage",
    "button.addSuccess": "Add Success",
    "button.addFailure": "Add Failure",
    "button.removeSuccess": "Remove Success",
    "button.removeFailure": "Remove Failure",
    "button.apply": "Apply",
    "button.cancel": "Cancel",
    "button.confirm": "Confirm",
    "button.customHp": "Custom HP",
    "button.breakConcentrationAll": "Break concentration - all concentration buffs end",
    "character.breakConcentration": "Break Concentration",
    "character.breakConcentrationAll": "Break concentration - all concentration buffs end",
    "character.addSuccess": "Add Success",
    "character.addFailure": "Add Failure",
    "character.removeSuccess": "Remove Success",
    "character.removeFailure": "Remove Failure",
    "character.hpAuto": "Automatic HP",
    "character.hpCustom": "Custom HP enabled",
    "sheet.stats": "Stats",
    "sheet.combatStats": "Combat Stats",
    "sheet.passiveStats": "Passive Stats",
    "sheet.perception": "Perception",
    "sheet.insight": "Insight",
    "sheet.investigation": "Investigation",
    "sheet.inventory": "Inventory",
    "sheet.currency": "Currency",
    "sheet.skills": "Skills",
    "sheet.spells": "Spells",
    "sheet.spellcastingStats": "Spellcasting Stats",
    "sheet.hitDice": "Hit Dice",
    "sheet.deathSaves": "Death Saves",
    "sheet.featuresTraits": "Features & Traits",
    "sheet.attacks": "Attacks",
    "sheet.otherProficiencies": "Other Proficiencies & Languages",
    "sheet.appearanceBio": "Appearance & Bio",
    "sheet.levelXp": "Level & Experience",
    "sheet.identity": "Identity",
    "sheet.savingThrows": "Saving Throws",
    "sheet.expertise": "Expertise",
    "sheet.expertiseLabel": "EXPERTISE",
    "sheet.bgLabel": "BG",
    "sheet.locked": "Locked",
    "sheet.alreadyKnown": "Already known",
    "sheet.selected": "Selected",
    "sheet.fromHigherLevel": "From higher level",
    "sheet.expLabel": "EXP",
    "sheet.raceLabel": "Race",
    "sheet.classLabel": "Class",
    "sheet.noBio": "No bio information",
    "sheet.noFeaturesInfo": "No feature selections required at this time.",
    "sheet.pointsRemaining": "Points Remaining",
    "sheet.targetLevel": "Target Level",
    "sheet.tasks": "Tasks",
    "sheet.hitPoints": "Hit Points",
    "sheet.proficiencyBonus": "Proficiency Bonus",
    "sheet.classFeatures": "Class Features",
    "sheet.newFeatures": "New Features",
    "sheet.attacksConfigured": "No attacks configured",
    "sheet.noItemsInfo": "No items",
    "sheet.noCurrencyInfo": "No currency",
    "sheet.noFeaturesInfo2": "No features",
    "sheet.grantedEquipment": "Granted Equipment",
    "sheet.choose": "Choose",
    "sheet.stable": "Stable",
    "sheet.dead": "Dead",
    "sheet.customHpEnabled": "Custom HP enabled",
    "sheet.passive": "Passive",
    "sheet.racial": "Racial",
    "sheet.unlimited": "Unlimited",
    "sheet.none": "None",
    "sheet.referenceOnly": "Reference only",
    "sheet.musicalInstrument": "Musical instrument",
    "creator.selectRace": "Select Race",
    "creator.selectClass": "Select Class",
    "creator.selectSubclass": "Select Subclass",
    "creator.selectFeat": "Select Feat",
    "creator.chooseExpertise": "Select Expertise",
    "creator.rollHp": "Roll HP",
    "creator.confirmHp": "Confirm HP",
    "creator.improveAbilityScores": "Improve Ability Scores",
    "creator.takeFeat": "Take a Feat",
    "creator.completeAsi": "Complete Ability Score Improvement",
    "creator.selectExpertise": "Select Expertise",
    "creator.createCharacter": "Create Character",
    "creator.startingLevel": "Starting Level",
    "creator.chooseLevel": "Choose your character's starting level...",
    "creator.levelSummary": "Level {level} Summary",
    "creator.selectSkills": "Select Skills",
    "creator.selectEquipment": "Select Equipment",
    "creator.chooseRulebooks": "Choose Rulebooks",
    "creator.booksSelected": "Books selected",
    "creator.noFeatureSelections": "No feature selections required at this time.",
    "creator.selectSkillsFromList": "Select {n} skills from your class list ({current} of {max} selected)",
    "creator.identity": "Identity",
    "creator.race": "Race",
    "creator.class": "Class",
    "creator.abilityScores": "Ability Scores",
    "creator.background": "Background",
    "creator.skills": "Skills",
    "creator.equipment": "Equipment",
    "creator.spells": "Spells",
    "creator.subclass": "Subclass",
    "creator.finalTouches": "Final Touches",
    "creator.selectClassFirst": "Select a class first.",
    "creator.noSpellcasting": "Your class does not have spellcasting abilities.",
    "creator.noFeatureSelectionsInfo": "No feature selections required at this time.",
    "creator.levelSummaryTitle": "Level {level} Summary",
    "creator.selectSkillsText": "Select {n} skills from your class list ({current} of {max} selected)",
    "creator.chooseFeat": "Choose Feat",
    "creator.choosePersonalityTrait": "Choose Personality Trait",
    "creator.chooseIdeal": "Choose Ideal",
    "creator.chooseBond": "Choose Bond",
    "creator.chooseFlaw": "Choose Flaw",
    "creator.subclassHint": "Choose your {class} subclass. You unlock subclass features starting at level {level}.",
    "creator.raceHint": "Choose your character's race. Each race has unique traits, ability bonuses, and special abilities.",
    "creator.classHint": "Choose your character's class. This determines your core abilities, hit points, and when you'll pick a subclass.",
    "creator.featureSelections": "Feature Selections",
    "creator.featureSelectionHint": "You must make a selection for {feature}. This is a class feature that requires you to choose from the available options.",
    "creator.selectedFeat": "Selected Feat",
    "creator.changeFeat": "Change Feat",
    "placeholder.selectLanguage": "Select language...",
    "placeholder.selectSkillOrTool": "Select skill or tool...",
    "placeholder.describeAppearance": "Describe your character's physical appearance...",
    "placeholder.describePersonality": "Describe your character's personality, ideals, bonds, and flaws...",
    "placeholder.whereFrom": "Where is your character from? What motivates them?",
    "placeholder.listAllies": "List allies, organizations, or contacts...",
    "placeholder.additionalFeatures": "Additional features or traits not listed elsewhere...",
    "placeholder.notableTreasure": "Treasure, magic items, or valuable items...",
    "placeholder.additionalProficiencies": "List skills, languages, or other abilities...",
    "placeholder.e.g27": "e.g. 27",
    "placeholder.e.g6ft2": "e.g. 6'2\"",
    "placeholder.e.g180lbs": "e.g. 180 lbs",
    "placeholder.e.gBlue": "e.g. Blue",
    "placeholder.e.gBrown": "e.g. Brown",
    "placeholder.e.gFair": "e.g. Fair",
    "creator.selectSkillsFromClass": "Select {max} skills from your class list ({current} of {max} selected)",
    "button.addSpells": "Add Spells",
    "creator.chooseSubclass": "Choose Subclass",
    "creator.applyAsi": "Apply ASI",
    "creator.confirmSelection": "Confirm Selection",
    "creator.confirmSelectionCount": "Confirm Selection ({n}/{max})",
    "creator.selectFromOptions": "Select from the options below",
    "creator.change": "Change",
    "creator.select": "Select",
    "wizard.back": "Back",
    "wizard.next": "Next",
    "wizard.save": "Save",
    "wizard.cancel": "Cancel",
    "wizard.confirm": "Confirm",
    "wizard.apply": "Apply",
    "wizard.close": "Close",
    "wizard.gotIt": "Got it",
    "wizard.edit": "Edit",
    "wizard.view": "View",
    "wizard.delete": "Delete",
    "wizard.remove": "Remove",
    "wizard.add": "Add",
    "wizard.search": "Search",
    "wizard.loading": "Loading...",
    "wizard.noData": "No data",
    "levelUp.newFeatures": "New Features",
    "levelUp.targetLevel": "Target Level",
    "levelUp.pointsRemaining": "Points Remaining",
    "spell.prepareSpells": "Prepare Spells",
    "spell.spellbook": "Spellbook",
    "spell.spellsKnown": "Spells Known",
    "spell.cantripsKnown": "Cantrips Known",
    "spell.spellSlots": "Spell Slots",
    "spell.pactBoon": "Pact Boon",
    "spell.pactBoonRequired": "Pact Boon Required",
    "spell.eldritchInvocations": "Eldritch Invocations",
    "spell.magicalSecrets": "Magical Secrets",
    "spell.additionalMagicalSecrets": "Additional Magical Secrets",
    "spell.replaceKnownSpell": "Replace Known Spell",
    "spell.bonusCantrip": "Bonus Cantrip",
    "spell.searchSpells": "Search spells...",
    "spell.expand": "Expand",
    "spell.collapse": "Collapse",
    "spell.restore": "Restore",
    "spell.use": "Use",
    "spell.expended": "Expended",
    "spell.total": "Total",
    "spell.remaining": "Remaining",
    "spell.level": "Level",
    "spell.damage": "Damage",
    "spell.healing": "Healing",
    "spell.tempHp": "Temp HP",
    "spell.range": "Range",
    "spell.save": "Save",
    "spell.target": "Target",
    "spell.duration": "Duration",
    "spell.school": "School",
    "spell.concentration": "Concentration",
    "spell.materialComponent": "Material Component",
    "spell.requires": "Requires",
    "spell.action": "Action",
    "spell.bonusAction": "Bonus Action",
    "spell.reaction": "Reaction",
    "spell.minute": "Minute",
    "spell.hour": "Hour",
    "spell.round": "Round",
    "spell.unlimited": "Unlimited",
    "spell.passive": "Passive",
    "spell.onUse": "On Use",
    "spell.endsIf": "Ends If",
    "spell.scales": "Scales",
    "spell.onHit": "On Hit",
    "spell.eachTurn": "Each Turn",
    "spell.onFail": "On Fail",
    "spell.onSave": "On Save",
    "spell.upcast": "Upcast",
    "spell.needs": "Needs",
    "feat.search": "Search...",
    "feat.prerequisites": "Prerequisites",
    "feat.none": "None",
    "feat.source": "Source",
    "feat.book": "Book",
    "feat.type": "Type",
    "feat.level": "Level",
    "feat.uses": "Uses",
    "feat.duration": "Duration",
    "feat.requires": "Requires",
    "feat.immune": "Immune",
    "feat.searchFeats": "Search feats...",
    "feat.searchSubclasses": "Search subclasses...",
    "feat.selectSubclass": "Select Subclass",
    "feat.selectRace": "Select Race",
    "feat.selectClass": "Select Class",
    "feat.applyAsi": "Apply ASI",
    "feat.changeFeat": "Change Feat",
    "feat.chooseFeat": "Choose Feat",
    "feat.selectFromOptions": "Select from the options below",
    "feat.confirmSelection": "Confirm Selection",
    "feat.confirmSelectionCount": "Confirm Selection ({n}/{max})",
    "equipment.addItem": "Add Item",
    "equipment.editItem": "Edit Custom Item",
    "equipment.itemName": "Item name",
    "equipment.itemDescription": "Item description...",
    "equipment.amount": "Amount",
    "equipment.enterAmount": "Enter amount...",
    "item.addFeature": "Add Feature",
    "button.addFeature": "Add Feature",
    "button.addSrdItem": "Add SRD Item",
    "button.addCustomItem": "Add Custom Item",
    "modal.editCustomItem": "Edit Custom Item",
    "modal.addCustomItem": "Add Custom Item",
    "item.addSpell": "Add Spell",
    "item.removeSpell": "Remove spell",
    "item.removeFeature": "Remove feature",
    "item.removeItem": "Remove item",
    "item.noItems": "No items",
    "item.noCurrency": "No currency",
    "item.noFeatures": "No features",
    "item.grantedEquipment": "Granted Equipment",
    "item.choose": "Choose",
    "item.addSRDItem": "Add SRD Item",
    "item.addCustomItem": "Add Custom Item",
    "item.searchPlaceholder": "Search...",
    "item.editPlaceholder": "Edit...",
    "admin.title": "Admin",
    "admin.testLab": "Admin Test Lab",
    "admin.runningTests": "Running tests...",
    "admin.refreshTests": "Refresh SRD Data Tests",
    "admin.backToAdmin": "Back to Admin",
    "admin.accessRequired": "Admin access required.",
    "admin.removeTestCharacters": "Remove Test Characters",
    "admin.debugLogin": "Debug login",
    "admin.openDebugTerminal": "Open debug terminal",
    "admin.aboutRulebooks": "About Rulebooks",
    "admin.generateTest": "Generate Test Characters",
    "admin.confirmGenerate": "Generate Test Characters",
    "admin.confirmGenerateText": "This will generate {n} test characters covering all class/subclass combinations. Continue?",
    "admin.confirmRemove": "Remove Test Characters",
    "admin.confirmRemoveText": "This will permanently delete all test characters. Continue?",
    "admin.generatingProgress": "Generating test characters...",
    "admin.generatedResults": "Generated {generationResults.length} characters — {succeeded} succeeded, {failed} failed",
    "admin.dismissResults": "Dismiss generation results",
    "admin.validationReport": "Validation Report — {passed} passed, {failed} failed, {warnings} warnings",
    "admin.copyAiSummary": "Copy AI Summary",
    "admin.collapse": "Collapse",
    "admin.expand": "Expand",
    "admin.pass": "PASS",
    "admin.fail": "FAIL",
    "admin.warn": "WARN",
    "admin.noTestCharacters": "No test characters yet. Generate them from the admin panel.",
    "admin.srdDataTests": "SRD Data Tests",
    "admin.removedTestCharacters": "Removed {n} test character{n}",
    "admin.filterAll": "All",
    "admin.filterFailures": "Failures",
    "admin.filterWarnings": "Warnings",
    "admin.filterPassing": "Passing",
    "admin.dismissValidation": "Dismiss validation report",
    "admin.exportJson": "Export {char.name} as JSON",
    "admin.deleteChar": "Delete {char.name}",
    "admin.returnHome": "Return Home",
    "admin.characterLevel": "Level {level} {class} — {subclass}",
    "admin.testCharactersCount": "Test Characters ({count})",
    "admin.generating": "Generating...",
    "admin.generateError": "Failed to generate test characters.",
    "admin.removeError": "Failed to remove test characters.",
    "admin.noReportLoaded": "No report loaded",
    "dice.rollTheBones": "Roll the bones",
    "dice.test3d": "Test 3D",
    "dice.characterFigures": "Character Figures",
    "dice.roller": "Dice Roller",
    "dice.rollAll": "Roll All Dice",
    "dice.lastResult": "Last Result",
    "newPlayerTips.title": "New Player Tips",
    "newPlayerTips.close": "Close",
    "export.json": "Export {char.name} as JSON",
    "delete.confirm": "Are you sure you want to delete {char.name}? This action cannot be undone.",
    "import.pdfError": "This PDF doesn't contain DND Wizard character data.",
    "import.jsonError": "Failed to import character JSON.",
    "import.success": 'Imported "{name}" successfully.',
    "noData.characters": "No characters yet. Create your first character!",
    "home.importPdf": "Import PDF",
    "home.importJson": "Import JSON",
    "home.backupAll": "Backup All Characters",
    "home.adminLab": "Admin Test Lab",
    "home.noCharacters": "No characters yet. Create your first hero to begin your adventure.",
    "home.unnamedHero": "Unnamed Hero",
    "home.created": "Created",
    "home.adminTestLab": "Admin Test Lab",
    "home.myCharacters": "My Characters",
    "form.characterName": "Character Name",
    "form.characterNameRequired": "Character Name *",
    "form.playerName": "Player Name",
    "form.race": "Race",
    "form.class": "Class",
    "form.background": "Background",
    "form.alignment": "Alignment",
    "form.languages": "Languages",
    "form.raceOptions": "Race Options",
    "form.toolProficiencies": "Tool Proficiencies",
    "form.spellcastingAbility": "Spellcasting Ability",
    "form.spellSaveDC": "Spell Save DC",
    "form.spellAttackBonus": "Spell Attack Bonus",
    "form.total": "Total",
    "form.remaining": "Remaining",
    "form.level": "Level",
    "form.currentXp": "Current XP",
    "form.maxXp": "Max XP",
    "form.age": "Age",
    "form.height": "Height",
    "form.weight": "Weight",
    "form.eyes": "Eyes",
    "form.skin": "Skin",
    "form.hair": "Hair",
    "form.characterAppearance": "Character Appearance",
    "form.personality": "Personality",
    "form.backstory": "Backstory",
    "form.allies": "Allies & Organizations",
    "form.additionalFeatures": "Additional Features & Traits",
    "form.treasure": "Treasure",
    "form.enterCharacterName": "Enter character name",
    "form.yourName": "Your name",
    "form.e.gFolkHero": "e.g. Folk Hero",
    "form.e.g10d8": "e.g. 10d8",
    "form.zero": "0",
    "form.e.g27": "e.g. 27",
    "form.e.g6ft2": "e.g. 6'2\"",
    "form.e.g180lbs": "e.g. 180 lbs",
    "form.e.gBlue": "e.g. Blue",
    "form.e.gFair": "e.g. Fair",
    "form.e.gBrown": "e.g. Brown",
    "form.describeAppearance": "Describe your character's physical appearance...",
    "form.describePersonality": "Describe your character's personality traits, ideals, bonds, and flaws...",
    "form.whereFrom": "Where did your character come from? What drives them?",
    "form.listAllies": "List allies, organizations, or contacts...",
    "form.additionalFeaturesDesc": "Any additional features or traits not listed elsewhere...",
    "form.notableTreasure": "Notable treasure, magic items, or valuables...",
    "form.additionalProficiencies": "List any additional proficiencies, languages, or other notable abilities...",
    "form.selectSkillOrTool": "Select skill or tool...",
    "form.describePersonalityShort": "Describe your character's personality...",
    "form.writeBackstory": "Write your character's backstory...",
    "form.e.g62inch": "e.g., 6'2\"",
    "form.e.g180lbs2": "e.g., 180 lbs",
    "form.e.gBlue2": "e.g., Blue",
    "form.e.gBrownCurly": "e.g., Brown, curly",
    "form.e.gFairTanned": "e.g., Fair, tanned",
    "creator.selectBackground": "Select background",
    "creator.selectAlignment": "Select alignment",
    "creator.identityHint": "Enter your character's name, choose a background, and set their alignment. This is who your character is in the world.",
    "form.selectBackground": "Select background",
    "form.selectAlignment": "Select alignment",
    "character.levelUp": "Level Up",
    "character.exportPdf": "Export PDF",
    "character.exportJson": "Export JSON",
    "character.delete": "Delete Character",
    "character.saved": "Saved",
    "character.endTurn": "End Turn",
    "character.notFound": "Character Not Found",
    "character.notFoundDesc": "This character could not be found. It may have been deleted.",
    "race.Dragonborn": "Dragonborn",
    "race.Dwarf": "Dwarf",
    "race.Elf": "Elf",
    "race.Gnome": "Gnome",
    "race.Half-Elf": "Half-Elf",
    "race.Halfling": "Halfling",
    "race.Half-Orc": "Half-Orc",
    "race.Human": "Human",
    "race.Tiefling": "Tiefling",
    "race.Aarakocra": "Aarakocra",
    "race.Genasi": "Genasi",
    "race.Goliath": "Goliath",
    "race.Kenku": "Kenku",
    "race.Tabaxi": "Tabaxi",
    "race.Triton": "Triton",
    "race.Bugbear": "Bugbear",
    "race.Goblin": "Goblin",
    "race.Hobgoblin": "Hobgoblin",
    "race.Kobold": "Kobold",
    "race.Orc": "Orc",
    "race.Yuan-ti Pureblood": "Yuan-ti Pureblood",
    "race.Feral Tiefling": "Feral Tiefling",
    "race.Aasimar": "Aasimar",
    "race.Firbolg": "Firbolg",
    "race.Kalashtar": "Kalashtar",
    "race.Shifter": "Shifter",
    "race.Warforged": "Warforged",
    "race.Changeling": "Changeling",
    "race.Eladrin": "Eladrin",
    "race.Sea Elf": "Sea Elf",
    "race.Shadar-kai": "Shadar-kai",
    "race.High Elf": "High Elf",
    "race.Wood Elf": "Wood Elf",
    "race.Dark Elf (Drow)": "Dark Elf (Drow)",
    "race.Hill Dwarf": "Hill Dwarf",
    "race.Mountain Dwarf": "Mountain Dwarf",
    "race.Lightfoot Halfling": "Lightfoot Halfling",
    "race.Stout Halfling": "Stout Halfling",
    "race.Rock Gnome": "Rock Gnome",
    "race.Forest Gnome": "Forest Gnome",
    "race.Half-Drow": "Half-Drow",
    "class.Barbarian": "Barbarian",
    "class.Bard": "Bard",
    "class.Cleric": "Cleric",
    "class.Druid": "Druid",
    "class.Fighter": "Fighter",
    "class.Monk": "Monk",
    "class.Paladin": "Paladin",
    "class.Ranger": "Ranger",
    "class.Rogue": "Rogue",
    "class.Sorcerer": "Sorcerer",
    "class.Warlock": "Warlock",
    "class.Wizard": "Wizard",
    "class.Artificer": "Artificer",
    "background.Acolyte": "Acolyte",
    "background.Charlatan": "Charlatan",
    "background.Criminal": "Criminal",
    "background.Entertainer": "Entertainer",
    "background.Folk Hero": "Folk Hero",
    "background.Guild Artisan": "Guild Artisan",
    "background.Hermit": "Hermit",
    "background.Noble": "Noble",
    "background.Outlander": "Outlander",
    "background.Sage": "Sage",
    "background.Sailor": "Sailor",
    "background.Soldier": "Soldier",
    "background.Urchin": "Urchin",
    "skill.Acrobatics": "Acrobatics",
    "skill.Animal Handling": "Animal Handling",
    "skill.Arcana": "Arcana",
    "skill.Athletics": "Athletics",
    "skill.Deception": "Deception",
    "skill.History": "History",
    "skill.Insight": "Insight",
    "skill.Intimidation": "Intimidation",
    "skill.Investigation": "Investigation",
    "skill.Medicine": "Medicine",
    "skill.Nature": "Nature",
    "skill.Perception": "Perception",
    "skill.Performance": "Performance",
    "skill.Persuasion": "Persuasion",
    "skill.Religion": "Religion",
    "skill.Sleight of Hand": "Sleight of Hand",
    "skill.Stealth": "Stealth",
    "skill.Survival": "Survival",
    "feature.Darkvision": "Darkvision",
    "feature.Fey Ancestry": "Fey Ancestry",
    "feature.Trance": "Trance",
    "equipment.Armor": "Armor",
    "equipment.Weapons": "Weapons",
    "equipment.Adventuring Gear": "Adventuring Gear",
    "equipment.Tools": "Tools",
    "damage.Bludgeoning": "Bludgeoning",
    "damage.Piercing": "Piercing",
    "damage.Slashing": "Slashing",
    "spellSchool.Abjuration": "Abjuration",
    "spellSchool.Conjuration": "Conjuration",
    "spellSchool.Divination": "Divination",
    "spellSchool.Enchantment": "Enchantment",
    "spellSchool.Evocation": "Evocation",
    "spellSchool.Illusion": "Illusion",
    "spellSchool.Necromancy": "Necromancy",
    "spellSchool.Transmutation": "Transmutation",
    "alignment.Lawful Good": "Lawful Good",
    "alignment.Neutral Good": "Neutral Good",
    "alignment.Chaotic Good": "Chaotic Good",
    "alignment.Lawful Neutral": "Lawful Neutral",
    "alignment.True Neutral": "True Neutral",
    "alignment.Chaotic Neutral": "Chaotic Neutral",
    "alignment.Lawful Evil": "Lawful Evil",
    "alignment.Neutral Evil": "Neutral Evil",
    "alignment.Chaotic Evil": "Chaotic Evil",
    "section.combatStats": "Combat Stats",
    "section.passiveStats": "Passive Stats",
    "section.deathSaves": "Death Saves",
    "section.hitDice": "Hit Dice",
    "section.featuresTraits": "Features & Traits",
    "section.spellcastingStats": "Spellcasting Stats",
    "section.appearanceBio": "Appearance & Bio",
    "section.otherProficiencies": "Other Proficiencies & Languages",
    "section.levelXp": "Level & Experience",
    "section.attacks": "Attacks",
    "section.inventory": "Inventory",
    "section.currency": "Currency",
    "section.skills": "Skills",
    "section.spells": "Spells",
    "section.stats": "Stats",
    "section.identity": "Identity",
    "section.savingThrows": "Saving Throws",
    "section.expertise": "Expertise",
  },
  id: {
    "app.name": "DND Wizard",
    "nav.home": "Beranda",
    "nav.new": "Baru",
    "nav.myCharacters": "Karakter Saya",
    "common.back": "Kembali",
    "common.next": "Lanjut",
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.confirm": "Konfirmasi",
    "common.apply": "Terapkan",
    "common.close": "Tutup",
    "common.edit": "Edit",
    "common.view": "Lihat",
    "common.delete": "Hapus",
    "common.remove": "Hapus",
    "common.add": "Tambah",
    "common.search": "Cari",
    "common.loading": "Memuat...",
    "common.noData": "Tidak ada data",
    "common.gotIt": "Mengerti",
    "theme.toggle.light": "Ganti ke mode terang",
    "theme.toggle.dark": "Ganti ke mode gelap",
    "description.show": "Tampilkan deskripsi",
    "description.hide": "Sembunyikan deskripsi",
    "character.identity": "Identitas",
    "character.race": "Ras",
    "character.class": "Kelas",
    "character.abilityScores": "Nilai Keampuan",
    "character.background": "Latar Belakang",
    "character.skills": "Keterampilan",
    "character.equipment": "Peralatan",
    "character.spells": "Sihir",
    "character.subclass": "Subclass",
    "character.finalTouches": "Sentuhan Akhir",
    "character.level": "Level",
    "character.xp": "Poin Pengalaman",
    "character.hp": "Poin HP",
    "character.currentHp": "HP Saat Ini",
    "character.maxHp": "HP Maks",
    "character.tempHp": "HP Sementara",
    "character.speed": "Kecepatan",
    "character.proficiency": "Bonus Keahlian",
    "character.inventory": "Inventaris",
    "character.currency": "Mata Uang",
    "character.spellcasting": "Penusukan Sihir",
    "character.features": "Fitur",
    "character.traits": "Sifat",
    "character.languages": "Bahasa",
    "character.deathSaves": "Roll Kematian",
    "character.stable": "Stabil",
    "character.dead": "Mati",
    "status.dead": "Mati",
    "character.success": "Berhasil",
    "character.failure": "Gagal",
    "character.attacks": "Serangan",
    "character.noAttacks": "Tidak ada serangan yang dikonfigurasi",
    "character.sheet": "Lembar Karakter",
    "character.returnHome": "Kembali ke Beranda",
    "character.editMode": "Mode Edit",
    "character.actions": "Aksi",
    "character.heal": "Pulih",
    "character.damage": "Kerusakan",
    "button.takeDamage": "Terima Kerusakan",
    "button.addSuccess": "Tambah Berhasil",
    "button.addFailure": "Tambah Gagal",
    "button.removeSuccess": "Hapus Berhasil",
    "button.removeFailure": "Hapus Gagal",
    "button.apply": "Terapkan",
    "button.cancel": "Batal",
    "button.confirm": "Konfirmasi",
    "button.customHp": "HP Kustom",
    "button.breakConcentrationAll": "Pecah konsentrasi - semua efek konsentrasi berakhir",
    "character.breakConcentration": "Pecah Konsentrasi",
    "character.breakConcentrationAll": "Pecah konsentrasi - semua efek konsentrasi berakhir",
    "character.addSuccess": "Tambah Berhasil",
    "character.addFailure": "Tambah Gagal",
    "character.removeSuccess": "Hapus Berhasil",
    "character.removeFailure": "Hapus Gagal",
    "character.hpAuto": "HP Otomatis",
    "character.hpCustom": "HP Kustom aktif",
    "character.levelUp": "Level Up",
    "character.exportPdf": "Ekspor PDF",
    "character.exportJson": "Ekspor JSON",
    "character.delete": "Hapus Karakter",
    "character.saved": "Tersimpan",
    "character.endTurn": "Akhiri Ronde",
    "character.notFound": "Karakter Tidak Ditemukan",
    "character.notFoundDesc": "Karakter ini tidak dapat ditemukan. Mungkin telah dihapus.",
    "sheet.stats": "Status",
    "sheet.combatStats": "Status Combat",
    "sheet.passiveStats": "Status Pasif",
    "sheet.perception": "Persepsi",
    "sheet.insight": "Wawasan",
    "sheet.investigation": "Investigasi",
    "sheet.inventory": "Inventaris",
    "sheet.currency": "Mata Uang",
    "sheet.skills": "Keterampilan",
    "sheet.spells": "Sihir",
    "sheet.spellcastingStats": "Status Penusukan Sihir",
    "sheet.hitDice": "Dadu HP",
    "sheet.deathSaves": "Roll Kematian",
    "sheet.featuresTraits": "Fitur & Sifat",
    "sheet.attacks": "Serangan",
    "sheet.otherProficiencies": "Keahlian & Bahasa Lainnya",
    "sheet.appearanceBio": "Penampilan & Bio",
    "sheet.levelXp": "Level & Pengalaman",
    "sheet.identity": "Identitas",
    "sheet.savingThrows": "Roll Saving",
    "sheet.expertise": "Keahlian",
    "sheet.expertiseLabel": "KEAHLIAN",
    "sheet.bgLabel": "LB",
    "sheet.locked": "Terkunci",
    "sheet.alreadyKnown": "Sudah diketahui",
    "sheet.selected": "Dipilih",
    "sheet.fromHigherLevel": "Dari level lebih tinggi",
    "sheet.expLabel": "EXP",
    "sheet.raceLabel": "Ras",
    "sheet.classLabel": "Kelas",
    "sheet.noBio": "Tidak ada informasi bio",
    "sheet.noFeaturesInfo": "Tidak ada pilihan fitur yang diperlukan saat ini.",
    "sheet.pointsRemaining": "Poin Tersisa",
    "sheet.targetLevel": "Target Level",
    "sheet.tasks": "Tugas",
    "sheet.hitPoints": "Poin HP",
    "sheet.proficiencyBonus": "Bonus Keahlian",
    "sheet.classFeatures": "Fitur Kelas",
    "sheet.newFeatures": "Fitur Baru",
    "sheet.attacksConfigured": "Tidak ada serangan yang dikonfigurasi",
    "sheet.noItemsInfo": "Tidak ada item",
    "sheet.noCurrencyInfo": "Tidak ada mata uang",
    "sheet.noFeaturesInfo2": "Tidak ada fitur",
    "sheet.grantedEquipment": "Peralatan Diberikan",
    "sheet.choose": "Pilih",
    "sheet.stable": "Stabil",
    "sheet.dead": "Mati",
    "sheet.customHpEnabled": "HP Kustom aktif",
    "sheet.passive": "Pasif",
    "sheet.racial": "Rasial",
    "sheet.unlimited": "Tidak terbatas",
    "sheet.none": "Tidak ada",
    "sheet.referenceOnly": "Hanya referensi",
    "sheet.musicalInstrument": "Alat musik",
    "creator.selectRace": "Pilih Ras",
    "creator.selectClass": "Pilih Kelas",
    "creator.selectSubclass": "Pilih Subclass",
    "creator.selectFeat": "Pilih Fitur",
    "creator.chooseExpertise": "Pilih Keahlian",
    "creator.rollHp": "Roll HP",
    "creator.confirmHp": "Konfirmasi HP",
    "creator.improveAbilityScores": "Tingkatkan Nilai Keampuan",
    "creator.takeFeat": "Ambil Fitur",
    "creator.completeAsi": "Selesaikan Peningkatan Nilai Keampuan",
    "creator.selectExpertise": "Pilih Keahlian",
    "creator.createCharacter": "Buat Karakter",
    "creator.startingLevel": "Level Awal",
    "creator.chooseLevel": "Pilih level awal karakter...",
    "creator.levelSummary": "Ringkasan Level {level}",
    "creator.selectSkills": "Pilih Keterampilan",
    "creator.selectEquipment": "Pilih Peralatan",
    "creator.chooseRulebooks": "Pilih Buku Aturan",
    "creator.booksSelected": "Buku dipilih",
    "creator.noFeatureSelections": "Tidak ada pilihan fitur yang diperlukan saat ini.",
    "creator.selectSkillsFromList": "Pilih {n} keterampilan dari daftar kelas ({current} dari {max} dipilih)",
    "creator.identity": "Identitas",
    "creator.race": "Ras",
    "creator.class": "Kelas",
    "creator.abilityScores": "Nilai Keampuan",
    "creator.background": "Latar Belakang",
    "creator.skills": "Keterampilan",
    "creator.equipment": "Peralatan",
    "creator.spells": "Sihir",
    "creator.subclass": "Subclass",
    "creator.finalTouches": "Sentuhan Akhir",
    "creator.selectClassFirst": "Pilih kelas terlebih dahulu.",
    "creator.noSpellcasting": "Kelasmu tidak memiliki kemampuan penusukan sihir.",
    "creator.noFeatureSelectionsInfo": "Tidak ada pilihan fitur yang diperlukan saat ini.",
    "creator.levelSummaryTitle": "Ringkasan Level {level}",
    "creator.selectSkillsText": "Pilih {n} keterampilan dari daftar kelas ({current} dari {max} dipilih)",
    "creator.chooseFeat": "Pilih Fitur",
    "creator.choosePersonalityTrait": "Pilih Sifat Kepribadian",
    "creator.chooseIdeal": "Pilih Ideal",
    "creator.chooseBond": "Pilih Ikatan",
    "creator.chooseFlaw": "Pilih Kelemahan",
    "creator.subclassHint": "Pilih subclass {class}. Kamu akan membuka fitur subclass mulai level {level}.",
    "creator.raceHint": "Pilih ras karaktermu. Setiap ras memiliki ciri khas, bonus kemampuan, dan kemampuan khusus yang unik.",
    "creator.classHint": "Pilih kelas karaktermu. Ini menentukan kemampuan dasar, poin HP, dan kapan kamu akan memilih subclass.",
    "creator.featureSelections": "Pilihan Fitur",
    "creator.featureSelectionHint": "Kamu harus membuat pilihan untuk {feature}. Ini adalah fitur kelas yang memerlukan kamu untuk memilih dari opsi yang tersedia.",
    "creator.selectedFeat": "Fitur Terpilih",
    "creator.changeFeat": "Ubah Fitur",
    "placeholder.selectLanguage": "Pilih bahasa...",
    "placeholder.selectSkillOrTool": "Pilih keterampilan atau alat...",
    "placeholder.describeAppearance": "Deskripsikan penampilan fisik karaktermu...",
    "placeholder.describePersonality": "Deskripsikan sifat kepribadian, ideal, ikatan, dan kelemahan karaktermu...",
    "placeholder.whereFrom": "Dari mana karaktermu berasal? Apa yang memotivasinya?",
    "placeholder.listAllies": "Daftar sekutu, organisasi, atau kontak...",
    "placeholder.additionalFeatures": "Fitur atau sifat tambahan yang tidak tercantum di tempat lain...",
    "placeholder.notableTreasure": "Harta karun, barang ajaib, atau barang berharga...",
    "placeholder.additionalProficiencies": "Daftar keahlian, bahasa, atau kemampuan lain...",
    "placeholder.e.g27": "mis. 27",
    "placeholder.e.g6ft2": "mis. 6'2\"",
    "placeholder.e.g180lbs": "mis. 180 lbs",
    "placeholder.e.gBlue": "mis. Biru",
    "placeholder.e.gBrown": "mis. Coklat",
    "placeholder.e.gFair": "mis. Fair",
    "creator.selectSkillsFromClass": "Pilih {max} keterampilan dari daftar kelasmu ({current} dari {max} terpilih)",
    "button.addSpells": "Tambah Sihir",
    "creator.chooseSubclass": "Pilih Subclass",
    "creator.applyAsi": "Terapkan ASI",
    "creator.confirmSelection": "Konfirmasi Pilihan",
    "creator.confirmSelectionCount": "Konfirmasi Pilihan ({n}/{max})",
    "creator.selectFromOptions": "Pilih dari opsi di bawah ini",
    "creator.change": "Ganti",
    "creator.select": "Pilih",
    "wizard.back": "Kembali",
    "wizard.next": "Lanjut",
    "wizard.save": "Simpan",
    "wizard.cancel": "Batal",
    "wizard.confirm": "Konfirmasi",
    "wizard.apply": "Terapkan",
    "wizard.close": "Tutup",
    "wizard.gotIt": "Mengerti",
    "wizard.edit": "Edit",
    "wizard.view": "Lihat",
    "wizard.delete": "Hapus",
    "wizard.remove": "Hapus",
    "wizard.add": "Tambah",
    "wizard.search": "Cari",
    "wizard.loading": "Memuat...",
    "wizard.noData": "Tidak ada data",
    "levelUp.newFeatures": "Fitur Baru",
    "levelUp.targetLevel": "Target Level",
    "levelUp.pointsRemaining": "Poin Tersisa",
    "spell.prepareSpells": "Siapkan Sihir",
    "spell.spellbook": "Buku Sihir",
    "spell.spellsKnown": "Sihir Dikenal",
    "spell.cantripsKnown": "Cantrips Dikenal",
    "spell.spellSlots": "Slot Sihir",
    "spell.pactBoon": "Boon Pakta",
    "spell.pactBoonRequired": "Boon Pakta Diperlukan",
    "spell.eldritchInvocations": "Invocasi Eldritch",
    "spell.magicalSecrets": "Rahasia Magis",
    "spell.additionalMagicalSecrets": "Rahasia Magis Tambahan",
    "spell.replaceKnownSpell": "Ganti Sihir Dikenal",
    "spell.bonusCantrip": "Cantrip Bonus",
    "spell.searchSpells": "Cari sihir...",
    "spell.expand": "Bentangkan",
    "spell.collapse": "Ciutkan",
    "spell.restore": "Pulihkan",
    "spell.use": "Gunakan",
    "spell.expended": "Terpakai",
    "spell.total": "Total",
    "spell.remaining": "Sisa",
    "spell.level": "Level",
    "spell.damage": "Kerusakan",
    "spell.healing": "Penyembuhan",
    "spell.tempHp": "HP Sementara",
    "spell.range": "Jarak",
    "spell.save": "Save",
    "spell.target": "Target",
    "spell.duration": "Durasi",
    "spell.school": "Sekolah",
    "spell.concentration": "Konsentrasi",
    "spell.materialComponent": "Komponen Material",
    "spell.requires": "Membutuhkan",
    "spell.action": "Aksi",
    "spell.bonusAction": "Aksi Bonus",
    "spell.reaction": "Reaksi",
    "spell.minute": "Menit",
    "spell.hour": "Jam",
    "spell.round": "Ronde",
    "spell.unlimited": "Tidak terbatas",
    "spell.passive": "Pasif",
    "spell.onUse": "Saat Digunakan",
    "spell.endsIf": "Berakhir Jika",
    "spell.scales": "Berkembang",
    "spell.onHit": "Saat HIT",
    "spell.eachTurn": "Setiap Ronde",
    "spell.onFail": "Saat Gagal",
    "spell.onSave": "Saat Berhasil",
    "spell.upcast": "Upcast",
    "spell.needs": "Membutuhkan",
    "feat.search": "Cari...",
    "feat.prerequisites": "Prasyarat",
    "feat.none": "Tidak ada",
    "feat.source": "Sumber",
    "feat.book": "Buku",
    "feat.type": "Tipe",
    "feat.level": "Level",
    "feat.uses": "Penggunaan",
    "feat.duration": "Durasi",
    "feat.requires": "Membutuhkan",
    "feat.immune": "Immune",
    "feat.searchFeats": "Cari fitur...",
    "feat.searchSubclasses": "Cari subclass...",
    "feat.selectSubclass": "Pilih Subclass",
    "feat.selectRace": "Pilih Ras",
    "feat.selectClass": "Pilih Kelas",
    "feat.applyAsi": "Terapkan ASI",
    "feat.changeFeat": "Ganti Fitur",
    "feat.chooseFeat": "Pilih Fitur",
    "feat.selectFromOptions": "Pilih dari opsi di bawah ini",
    "feat.confirmSelection": "Konfirmasi Pilihan",
    "feat.confirmSelectionCount": "Konfirmasi Pilihan ({n}/{max})",
    "equipment.addItem": "Tambah Item",
    "equipment.editItem": "Edit Item Kustom",
    "equipment.itemName": "Nama item",
    "equipment.itemDescription": "Deskripsi item...",
    "equipment.amount": "Jumlah",
    "equipment.enterAmount": "Masukkan jumlah...",
    "item.addFeature": "Tambah Fitur",
    "button.addFeature": "Tambah Fitur",
    "button.addSrdItem": "Tambah Item SRD",
    "button.addCustomItem": "Tambah Item Kustom",
    "modal.editCustomItem": "Edit Item Kustom",
    "modal.addCustomItem": "Tambah Item Kustom",
    "item.addSpell": "Tambah Sihir",
    "item.removeSpell": "Hapus sihir",
    "item.removeFeature": "Hapus fitur",
    "item.removeItem": "Hapus item",
    "item.noItems": "Tidak ada item",
    "item.noCurrency": "Tidak ada mata uang",
    "item.noFeatures": "Tidak ada fitur",
    "item.grantedEquipment": "Peralatan Diberikan",
    "item.choose": "Pilih",
    "item.addSRDItem": "Tambah Item SRD",
    "item.addCustomItem": "Tambah Item Kustom",
    "item.searchPlaceholder": "Cari...",
    "item.editPlaceholder": "Edit...",
    "admin.title": "Admin",
    "admin.testLab": "Lab Test Admin",
    "admin.runningTests": "Menjalankan test...",
    "admin.refreshTests": "Perbarui Test Data SRD",
    "admin.backToAdmin": "Kembali ke Admin",
    "admin.accessRequired": "Akses admin diperlukan.",
    "admin.removeTestCharacters": "Hapus Karakter Test",
    "admin.debugLogin": "Login debug",
    "admin.openDebugTerminal": "Buka terminal debug",
    "admin.aboutRulebooks": "Tentang Buku Aturan",
    "admin.generateTest": "Hasilkan Karakter Test",
    "admin.confirmGenerate": "Hasilkan Karakter Test",
    "admin.confirmGenerateText": "Ini akan menghasilkan {n} karakter test mencakup semua kombinasi kelas/subclass. Lanjutkan?",
    "admin.confirmRemove": "Hapus Karakter Test",
    "admin.confirmRemoveText": "Ini akan menghapus semua karakter test secara permanen. Lanjutkan?",
    "admin.generatingProgress": "Menghasilkan karakter test...",
    "admin.generatedResults": "Karakter terhasil — {succeeded} berhasil, {failed} gagal",
    "admin.dismissResults": "Tutup hasil generasi",
    "admin.validationReport": "Laporan Validasi — {passed} lulus, {failed} gagal, {warnings} peringatan",
    "admin.copyAiSummary": "Salin Ringkasan AI",
    "admin.collapse": "Ciutkan",
    "admin.expand": "Bentangkan",
    "admin.pass": "LULUS",
    "admin.fail": "GAGAL",
    "admin.warn": "PERINGATAN",
    "admin.noTestCharacters": "Belum ada karakter test. Hasilkan dari panel admin.",
    "admin.srdDataTests": "Test Data SRD",
    "admin.removedTestCharacters": "{n} karakter test telah dihapus",
    "admin.filterAll": "Semua",
    "admin.filterFailures": "Gagal",
    "admin.filterWarnings": "Peringatan",
    "admin.filterPassing": "Lulus",
    "admin.dismissValidation": "Tutup laporan validasi",
    "admin.exportJson": "Ekspor {char.name} sebagai JSON",
    "admin.deleteChar": "Hapus {char.name}",
    "admin.returnHome": "Kembali ke Beranda",
    "admin.characterLevel": "Level {level} {class} — {subclass}",
    "admin.testCharactersCount": "Karakter Test ({count})",
    "admin.generating": "Menghasilkan...",
    "admin.generateError": "Gagal menghasilkan karakter test.",
    "admin.removeError": "Gagal menghapus karakter test.",
    "admin.noReportLoaded": "Tidak ada laporan yang dimuat",
    "dice.rollTheBones": "Roll dadu",
    "dice.test3d": "Test 3D",
    "dice.characterFigures": "Figur Karakter",
    "dice.roller": "Pembuat Dadu",
    "dice.rollAll": "Roll Semua Dadu",
    "dice.lastResult": "Hasil Terakhir",
    "newPlayerTips.title": "Tips Pemain Baru",
    "newPlayerTips.close": "Tutup",
    "export.json": "Ekspor {char.name} sebagai JSON",
    "delete.confirm": "Apakah Anda yakin ingin menghapus {char.name}? Tindakan ini tidak bisa dibatalkan.",
    "import.pdfError": "PDF ini tidak berisi data karakter DND Wizard.",
    "import.jsonError": "Gagal mengimpor JSON karakter.",
    "import.success": 'Berhasil mengimpor "{name}".',
    "noData.characters": "Belum ada karakter. Buat karakter pertama Anda!",
    "home.importPdf": "Impor PDF",
    "home.importJson": "Impor JSON",
    "home.backupAll": "Cadangkan Semua Karakter",
    "home.adminLab": "Lab Test Admin",
    "home.noCharacters": "Belum ada karakter. Buat karakter pertamamu untuk memulai petualangan!",
    "home.unnamedHero": "Pahlawan Tanpa Nama",
    "home.created": "Dibuat",
    "home.adminTestLab": "Lab Test Admin",
    "home.myCharacters": "Karakter Saya",
    "form.characterName": "Nama Karakter",
    "form.characterNameRequired": "Nama Karakter *",
    "form.playerName": "Nama Pemain",
    "form.race": "Ras",
    "form.class": "Kelas",
    "form.background": "Latar Belakang",
    "form.alignment": "Selaras",
    "form.languages": "Bahasa",
    "form.raceOptions": "Opsi Ras",
    "form.toolProficiencies": "Keahlian Alat",
    "form.spellcastingAbility": "Kemampuan Penusukan Sihir",
    "form.spellSaveDC": "DC Save Sihir",
    "form.spellAttackBonus": "Bonus Serangan Sihir",
    "form.total": "Total",
    "form.remaining": "Sisa",
    "form.level": "Level",
    "form.currentXp": "XP Saat Ini",
    "form.maxXp": "XP Maks",
    "form.age": "Usia",
    "form.height": "Tinggi",
    "form.weight": "Berat",
    "form.eyes": "Mata",
    "form.skin": "Kulit",
    "form.hair": "Rambut",
    "form.characterAppearance": "Penampilan Karakter",
    "form.personality": "Kepribadian",
    "form.backstory": "Latar Belakang",
    "form.allies": "Sekutu & Organisasi",
    "form.additionalFeatures": "Fitur & Sifat Tambahan",
    "form.treasure": "Harta Karun",
    "form.enterCharacterName": "Masukkan nama karakter",
    "form.yourName": "Namamu",
    "form.e.gFolkHero": "mis. Pahlawan Rakyat",
    "form.e.g10d8": "mis. 10d8",
    "form.zero": "0",
    "form.e.g27": "mis. 27",
    "form.e.g6ft2": "mis. 6'2\"",
    "form.e.g180lbs": "mis. 180 lbs",
    "form.e.gBlue": "mis. Biru",
    "form.e.gFair": "mis. Terang",
    "form.e.gBrown": "mis. Coklat",
    "form.describeAppearance": "Deskripsikan penampilan fisik karaktermu...",
    "form.describePersonality": "Deskripsikan sifat kepribadian, ideal, ikatan, dan kelemahan karaktermu...",
    "form.whereFrom": "Dari mana karaktermu berasal? Apa yang memotivasinya?",
    "form.listAllies": "Daftar sekutu, organisasi, atau kontak...",
    "form.additionalFeaturesDesc": "Fitur atau sifat tambahan yang tidak tercantum di tempat lain...",
    "form.notableTreasure": "Harta karun, barang ajaib, atau barang berharga...",
    "form.additionalProficiencies": "Daftar keahlian, bahasa, atau kemampuan lain...",
    "form.selectSkillOrTool": "Pilih keterampilan atau alat...",
    "form.describePersonalityShort": "Deskripsikan kepribadian karaktermu...",
    "form.writeBackstory": "Tulis latar belakang karaktermu...",
    "form.e.g62inch": "mis., 6'2\"",
    "form.e.g180lbs2": "mis., 180 lbs",
    "form.e.gBlue2": "mis., Biru",
    "form.e.gBrownCurly": "mis., Coklat, keriting",
    "form.e.gFairTanned": "mis., Terang, sawo matang",
    "race.Dragonborn": "Dragonborn",
    "race.Dwarf": "Dwarf",
    "race.Elf": "Elf",
    "race.Gnome": "Gnome",
    "race.Half-Elf": "Half-Elf",
    "race.Halfling": "Halfling",
    "race.Half-Orc": "Half-Orc",
    "race.Human": "Manusia",
    "race.Tiefling": "Tiefling",
    "race.Aarakocra": "Aarakocra",
    "race.Genasi": "Genasi",
    "race.Goliath": "Goliath",
    "race.Kenku": "Kenku",
    "race.Tabaxi": "Tabaxi",
    "race.Triton": "Triton",
    "race.Bugbear": "Bugbear",
    "race.Goblin": "Goblin",
    "race.Hobgoblin": "Hobgoblin",
    "race.Kobold": "Kobold",
    "race.Orc": "Orc",
    "race.Yuan-ti Pureblood": "Yuan-ti Pureblood",
    "race.Feral Tiefling": "Feral Tiefling",
    "race.Aasimar": "Aasimar",
    "race.Firbolg": "Firbolg",
    "race.Kalashtar": "Kalashtar",
    "race.Shifter": "Shifter",
    "race.Warforged": "Warforged",
    "race.Changeling": "Changeling",
    "race.Eladrin": "Eladrin",
    "race.Sea Elf": "Sea Elf",
    "race.Shadar-kai": "Shadar-kai",
    "race.High Elf": "High Elf",
    "race.Wood Elf": "Wood Elf",
    "race.Dark Elf (Drow)": "Dark Elf (Drow)",
    "race.Hill Dwarf": "Hill Dwarf",
    "race.Mountain Dwarf": "Mountain Dwarf",
    "race.Lightfoot Halfling": "Lightfoot Halfling",
    "race.Stout Halfling": "Stout Halfling",
    "race.Rock Gnome": "Rock Gnome",
    "race.Forest Gnome": "Forest Gnome",
    "race.Half-Drow": "Half-Drow",
    "class.Barbarian": "Barbarian",
    "class.Bard": "Bard",
    "class.Cleric": "Cleric",
    "class.Druid": "Druid",
    "class.Fighter": "Fighter",
    "class.Monk": "Monk",
    "class.Paladin": "Paladin",
    "class.Ranger": "Ranger",
    "class.Rogue": "Rogue",
    "class.Sorcerer": "Sorcerer",
    "class.Warlock": "Warlock",
    "class.Wizard": "Wizard",
    "class.Artificer": "Artificer",
    "background.Acolyte": "Akolyt",
    "background.Charlatan": "Penipu",
    "background.Criminal": "Kriminal",
    "background.Entertainer": "Penghibur",
    "background.Folk Hero": "Pahlawan Rakyat",
    "background.Guild Artisan": "Pengrajin Guild",
    "background.Hermit": "Pertapa",
    "background.Noble": "Bangsawan",
    "background.Outlander": "Pendatang",
    "background.Sage": "Cendekiawan",
    "background.Sailor": "Pelaut",
    "background.Soldier": "Prajurit",
    "background.Urchin": "Anak Jalanan",
    "skill.Acrobatics": "Acrobatics",
    "skill.Animal Handling": "Animal Handling",
    "skill.Arcana": "Arcana",
    "skill.Athletics": "Athletics",
    "skill.Deception": "Deception",
    "skill.History": "History",
    "skill.Insight": "Insight",
    "skill.Intimidation": "Intimidation",
    "skill.Investigation": "Investigation",
    "skill.Medicine": "Medicine",
    "skill.Nature": "Nature",
    "skill.Perception": "Perception",
    "skill.Performance": "Performance",
    "skill.Persuasion": "Persuasion",
    "skill.Religion": "Religion",
    "skill.Sleight of Hand": "Sleight of Hand",
    "skill.Stealth": "Stealth",
    "skill.Survival": "Survival",
    "feature.Darkvision": "Darkvision",
    "feature.Fey Ancestry": "Fey Ancestry",
    "feature.Trance": "Trance",
    "equipment.Armor": "Armor",
    "equipment.Weapons": "Weapons",
    "equipment.Adventuring Gear": "Adventuring Gear",
    "equipment.Tools": "Tools",
    "damage.Bludgeoning": "Bludgeoning",
    "damage.Piercing": "Piercing",
    "damage.Slashing": "Slashing",
    "spellSchool.Abjuration": "Abjuration",
    "spellSchool.Conjuration": "Conjuration",
    "spellSchool.Divination": "Divination",
    "spellSchool.Enchantment": "Enchantment",
    "spellSchool.Evocation": "Evocation",
    "spellSchool.Illusion": "Illusion",
    "spellSchool.Necromancy": "Necromancy",
    "spellSchool.Transmutation": "Transmutation",
    "alignment.Lawful Good": "Lawful Good",
    "alignment.Neutral Good": "Neutral Good",
    "alignment.Chaotic Good": "Chaotic Good",
    "alignment.Lawful Neutral": "Lawful Neutral",
    "alignment.True Neutral": "True Neutral",
    "alignment.Chaotic Neutral": "Chaotic Neutral",
    "alignment.Lawful Evil": "Lawful Evil",
    "alignment.Neutral Evil": "Neutral Evil",
    "alignment.Chaotic Evil": "Chaotic Evil",
    "wizard.stepOf": "Step {step} of {total}",
    "section.combatStats": "Status Combat",
    "section.passiveStats": "Status Pasif",
    "section.deathSaves": "Roll Kematian",
    "section.hitDice": "Dadu HP",
    "section.featuresTraits": "Fitur & Sifat",
    "section.spellcastingStats": "Status Penusukan Sihir",
    "section.appearanceBio": "Penampilan & Bio",
    "section.otherProficiencies": "Keahlian & Bahasa Lainnya",
    "section.levelXp": "Level & Pengalaman",
    "section.attacks": "Serangan",
    "section.inventory": "Inventaris",
    "section.currency": "Mata Uang",
    "section.skills": "Keterampilan",
    "section.spells": "Sihir",
    "section.stats": "Status",
    "section.identity": "Identitas",
    "section.savingThrows": "Roll Saving",
    "section.expertise": "Keahlian",
    "section.backgroundSkills": "Keterampilan Latar Belakang",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("dnd-language") as Language | null;
    if (saved === "en" || saved === "id") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("dnd-language", lang);
  }, []);

  const t = useCallback(
    (key: string, fallback?: string) => {
      const dict = translations[language];
      if (dict && dict[key]) return dict[key];
      const enDict = translations.en;
      if (enDict && enDict[key]) return enDict[key];
      return fallback || key;
    },
    [language]
  );

  const tDesc = useCallback(
    (key: string, fallback: string) => {
      const dict = translations[language];
      if (dict && dict[key]) return dict[key];
      const enDict = translations.en;
      if (enDict && enDict[key]) return enDict[key];
      // Return fallback (English) with protected terms preserved
      return fallback;
    },
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t, tDesc }), [language, setLanguage, t, tDesc]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
