"use client";

import { createContext, useContext, useState, useEffect, useMemo, useCallback, type ReactNode } from "react";

export type Language = "en" | "id";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({ language: "en", setLanguage: () => {}, t: (k) => k });

export function useLanguage() {
  return useContext(LanguageContext);
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "DND Wizard",
    "nav.home": "Home",
    "nav.new": "New",
    "nav.myCharacters": "My Characters",
    "common.back": "Back",
    "common.next": "Next",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.apply": "Apply",
    "common.close": "Close",
    "common.edit": "Edit",
    "common.view": "View",
    "common.delete": "Delete",
    "common.remove": "Remove",
    "common.add": "Add",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.gotIt": "Got it",
    "theme.toggle.light": "Switch to light mode",
    "theme.toggle.dark": "Switch to dark mode",
    "description.show": "Show descriptions",
    "description.hide": "Hide descriptions",
    "character.identity": "Identity",
    "character.race": "Race",
    "character.class": "Class",
    "character.abilityScores": "Ability Scores",
    "character.background": "Background",
    "character.skills": "Skills",
    "character.equipment": "Equipment",
    "character.spells": "Spells",
    "character.subclass": "Subclass",
    "character.finalTouches": "Final Touches",
    "character.level": "Level",
    "character.xp": "Experience Points",
    "character.hp": "Hit Points",
    "character.currentHp": "Current HP",
    "character.maxHp": "Max HP",
    "character.tempHp": "Temp HP",
    "character.speed": "Speed",
    "character.proficiency": "Proficiency Bonus",
    "character.inventory": "Inventory",
    "character.currency": "Currency",
    "character.spellcasting": "Spellcasting",
    "character.features": "Features",
    "character.traits": "Traits",
    "character.languages": "Languages",
    "character.deathSaves": "Death Saves",
    "character.stable": "Stable",
    "character.dead": "Dead",
    "character.success": "Success",
    "character.failure": "Failure",
    "character.attacks": "Attacks",
    "character.noAttacks": "No attacks configured",
    "sheet.stats": "Stats",
    "sheet.combatStats": "Combat Stats",
    "sheet.passiveStats": "Passive Stats",
    "sheet.perception": "Perception",
    "sheet.insight": "Insight",
    "sheet.investigation": "Investigation",
    "sheet.inventory": "Inventory",
    "sheet.currency": "Currency",
    "sheet.skills": "Skills",
    "sheet.spells": "Spells",
    "sheet.spellcastingStats": "Spellcasting Stats",
    "sheet.hitDice": "Hit Dice",
    "sheet.deathSaves": "Death Saves",
    "sheet.featuresTraits": "Features & Traits",
    "sheet.attacks": "Attacks",
    "sheet.otherProficiencies": "Other Proficiencies & Languages",
    "sheet.appearanceBio": "Appearance & Bio",
    "sheet.levelXp": "Level & Experience",
    "sheet.identity": "Identity",
    "sheet.savingThrows": "Saving Throws",
    "creator.selectRace": "Select Race",
    "creator.selectClass": "Select Class",
    "creator.selectSubclass": "Select Subclass",
    "creator.selectFeat": "Select Feat",
    "creator.chooseExpertise": "Select Expertise",
    "creator.rollHp": "Roll HP",
    "creator.confirmHp": "Confirm HP",
    "creator.improveAbilityScores": "Improve Ability Scores",
    "creator.takeFeat": "Take a Feat",
    "creator.completeAsi": "Complete Ability Score Improvement",
    "creator.selectExpertise": "Select Expertise",
    "creator.createCharacter": "Create Character",
    "creator.startingLevel": "Starting Level",
    "creator.chooseLevel": "Choose your character's starting level...",
    "creator.levelSummary": "Level {level} Summary",
    "creator.selectSkills": "Select Skills",
    "creator.selectEquipment": "Select Equipment",
    "creator.chooseRulebooks": "Choose Rulebooks",
    "creator.booksSelected": "Books selected",
    "creator.noFeatureSelections": "No feature selections required at this time.",
    "creator.selectSkillsFromList": "Select {n} skills from your class list ({current} of {max} selected)",
    "levelUp.newFeatures": "New Features",
    "levelUp.targetLevel": "Target Level",
    "levelUp.pointsRemaining": "Points Remaining",
    "spell.prepareSpells": "Prepare Spells",
    "spell.spellbook": "Spellbook",
    "spell.spellsKnown": "Spells Known",
    "spell.cantripsKnown": "Cantrips Known",
    "spell.spellSlots": "Spell Slots",
    "spell.pactBoon": "Pact Boon",
    "spell.pactBoonRequired": "Pact Boon Required",
    "spell.eldritchInvocations": "Eldritch Invocations",
    "spell.magicalSecrets": "Magical Secrets",
    "spell.additionalMagicalSecrets": "Additional Magical Secrets",
    "spell.replaceKnownSpell": "Replace Known Spell",
    "spell.bonusCantrip": "Bonus Cantrip",
    "spell.searchSpells": "Search spells...",
    "feat.searchFeats": "Search feats...",
    "feat.searchSubclasses": "Search subclasses...",
    "feat.selectSubclass": "Select Subclass",
    "feat.selectRace": "Select Race",
    "feat.selectClass": "Select Class",
    "feat.applyAsi": "Apply ASI",
    "feat.changeFeat": "Change Feat",
    "feat.chooseFeat": "Choose Feat",
    "equipment.addItem": "Add Item",
    "equipment.editItem": "Edit Custom Item",
    "equipment.itemName": "Item name",
    "equipment.itemDescription": "Item description...",
    "item.addFeature": "Add Feature",
    "item.addSpell": "Add Spell",
    "item.removeSpell": "Remove spell",
    "item.removeFeature": "Remove feature",
    "item.removeItem": "Remove item",
    "item.noItems": "No items",
    "item.noCurrency": "No currency",
    "item.noFeatures": "No features",
    "item.grantedEquipment": "Granted Equipment",
    "item.choose": "Choose",
    "admin.title": "Admin",
    "admin.testLab": "Admin Test Lab",
    "admin.runningTests": "Running tests...",
    "admin.refreshTests": "Refresh SRD Data Tests",
    "admin.backToAdmin": "Back to Admin",
    "admin.accessRequired": "Admin access required.",
    "admin.removeTestCharacters": "Remove Test Characters",
    "admin.debugLogin": "Debug login",
    "admin.openDebugTerminal": "Open debug terminal",
    "admin.aboutRulebooks": "About Rulebooks",
    "dice.rollTheBones": "Roll the bones",
    "dice.test3d": "Test 3D",
    "dice.characterFigures": "Character Figures",
    "newPlayerTips.title": "New Player Tips",
    "newPlayerTips.close": "Close",
    "export.json": "Export {char.name} as JSON",
    "delete.confirm": "Are you sure you want to delete {char.name}? This action cannot be undone.",
    "import.pdfError": "This PDF doesn't contain DND Wizard character data.",
    "import.jsonError": "Failed to import character JSON.",
    "import.success": 'Imported "{name}" successfully.',
    "noData.characters": "No characters yet. Create your first character!",
  },
  id: {
    "app.name": "DND Wizard",
    "nav.home": "Beranda",
    "nav.new": "Baru",
    "nav.myCharacters": "Karakter Saya",
    "common.back": "Kembali",
    "common.next": "Lanjut",
    "common.save": "Simpan",
    "common.cancel": "Batal",
    "common.confirm": "Konfirmasi",
    "common.apply": "Terapkan",
    "common.close": "Tutup",
    "common.edit": "Edit",
    "common.view": "Lihat",
    "common.delete": "Hapus",
    "common.remove": "Hapus",
    "common.add": "Tambah",
    "common.search": "Cari",
    "common.loading": "Memuat...",
    "common.noData": "Tidak ada data",
    "common.gotIt": "Mengerti",
    "theme.toggle.light": "Ganti ke mode terang",
    "theme.toggle.dark": "Ganti ke mode gelap",
    "description.show": "Tampilkan deskripsi",
    "description.hide": "Sembunyikan deskripsi",
    "character.identity": "Identitas",
    "character.race": "Ras",
    "character.class": "Kelas",
    "character.abilityScores": "Nilai Keampuan",
    "character.background": "Latar Belakang",
    "character.skills": "Keterampilan",
    "character.equipment": "Peralatan",
    "character.spells": "Sihir",
    "character.subclass": "Subclass",
    "character.finalTouches": "Sentuhan Akhir",
    "character.level": "Level",
    "character.xp": "Poin Pengalaman",
    "character.hp": "Poin HP",
    "character.currentHp": "HP Saat Ini",
    "character.maxHp": "HP Maks",
    "character.tempHp": "HP Sementara",
    "character.speed": "Kecepatan",
    "character.proficiency": "Bonus Keahlian",
    "character.inventory": "Inventaris",
    "character.currency": "Mata Uang",
    "character.spellcasting": "Penusukan Sihir",
    "character.features": "Fitur",
    "character.traits": "Sifat",
    "character.languages": "Bahasa",
    "character.deathSaves": "Roll Kematian",
    "character.stable": "Stabil",
    "character.dead": "Mati",
    "character.success": "Berhasil",
    "character.failure": "Gagal",
    "character.attacks": "Serangan",
    "character.noAttacks": "Tidak ada serangan yang dikonfigurasi",
    "sheet.stats": "Status",
    "sheet.combatStats": "Status Combat",
    "sheet.passiveStats": "Status Pasif",
    "sheet.perception": "Persepsi",
    "sheet.insight": "Wawasan",
    "sheet.investigation": "Investigasi",
    "sheet.inventory": "Inventaris",
    "sheet.currency": "Mata Uang",
    "sheet.skills": "Keterampilan",
    "sheet.spells": "Sihir",
    "sheet.spellcastingStats": "Status Penusukan Sihir",
    "sheet.hitDice": "Dadu HP",
    "sheet.deathSaves": "Roll Kematian",
    "sheet.featuresTraits": "Fitur & Sifat",
    "sheet.attacks": "Serangan",
    "sheet.otherProficiencies": "Keahlian & Bahasa Lainnya",
    "sheet.appearanceBio": "Penampilan & Bio",
    "sheet.levelXp": "Level & Pengalaman",
    "sheet.identity": "Identitas",
    "sheet.savingThrows": "Roll Saving",
    "creator.selectRace": "Pilih Ras",
    "creator.selectClass": "Pilih Kelas",
    "creator.selectSubclass": "Pilih Subclass",
    "creator.selectFeat": "Pilih Fitur",
    "creator.chooseExpertise": "Pilih Keahlian",
    "creator.rollHp": "Roll HP",
    "creator.confirmHp": "Konfirmasi HP",
    "creator.improveAbilityScores": "Tingkatkan Nilai Keampuan",
    "creator.takeFeat": "Ambil Fitur",
    "creator.completeAsi": "Selesaikan Peningkatan Nilai Keampuan",
    "creator.selectExpertise": "Pilih Keahlian",
    "creator.createCharacter": "Buat Karakter",
    "creator.startingLevel": "Level Awal",
    "creator.chooseLevel": "Pilih level awal karakter...",
    "creator.levelSummary": "Ringkasan Level {level}",
    "creator.selectSkills": "Pilih Keterampilan",
    "creator.selectEquipment": "Pilih Peralatan",
    "creator.chooseRulebooks": "Pilih Buku Aturan",
    "creator.booksSelected": "Buku dipilih",
    "creator.noFeatureSelections": "Tidak ada pilihan fitur yang diperlukan saat ini.",
    "creator.selectSkillsFromList": "Pilih {n} keterampilan dari daftar kelas ({current} dari {max} dipilih)",
    "levelUp.newFeatures": "Fitur Baru",
    "levelUp.targetLevel": "Target Level",
    "levelUp.pointsRemaining": "Poin Tersisa",
    "spell.prepareSpells": "Siapkan Sihir",
    "spell.spellbook": "Buku Sihir",
    "spell.spellsKnown": "Sihir Diketahui",
    "spell.cantripsKnown": "Cantrips Diketahui",
    "spell.spellSlots": "Slot Sihir",
    "spell.pactBoon": "Boon Pakta",
    "spell.pactBoonRequired": "Boon Pakta Diperlukan",
    "spell.eldritchInvocations": "Invocasi Eldritch",
    "spell.magicalSecrets": "Rahasia Magis",
    "spell.additionalMagicalSecrets": "Rahasia Magis Tambahan",
    "spell.replaceKnownSpell": "Ganti Sihir Dikenal",
    "spell.bonusCantrip": "Cantrip Bonus",
    "spell.searchSpells": "Cari sihir...",
    "feat.searchFeats": "Cari fitur...",
    "feat.searchSubclasses": "Cari subclass...",
    "feat.selectSubclass": "Pilih Subclass",
    "feat.selectRace": "Pilih Ras",
    "feat.selectClass": "Pilih Kelas",
    "feat.applyAsi": "Terapkan ASI",
    "feat.changeFeat": "Ganti Fitur",
    "feat.chooseFeat": "Pilih Fitur",
    "equipment.addItem": "Tambah Item",
    "equipment.editItem": "Edit Item Kustom",
    "equipment.itemName": "Nama item",
    "equipment.itemDescription": "Deskripsi item...",
    "item.addFeature": "Tambah Fitur",
    "item.addSpell": "Tambah Sihir",
    "item.removeSpell": "Hapus sihir",
    "item.removeFeature": "Hapus fitur",
    "item.removeItem": "Hapus item",
    "item.noItems": "Tidak ada item",
    "item.noCurrency": "Tidak ada mata uang",
    "item.noFeatures": "Tidak ada fitur",
    "item.grantedEquipment": "Peralatan Diberikan",
    "item.choose": "Pilih",
    "admin.title": "Admin",
    "admin.testLab": "Lab Test Admin",
    "admin.runningTests": "Menjalankan test...",
    "admin.refreshTests": "Perbarui Test Data SRD",
    "admin.backToAdmin": "Kembali ke Admin",
    "admin.accessRequired": "Akses admin diperlukan.",
    "admin.removeTestCharacters": "Hapus Karakter Test",
    "admin.debugLogin": "Login debug",
    "admin.openDebugTerminal": "Buka terminal debug",
    "admin.aboutRulebooks": "Tentang Buku Aturan",
    "dice.rollTheBones": "Roll dadu",
    "dice.test3d": "Test 3D",
    "dice.characterFigures": "Figur Karakter",
    "newPlayerTips.title": "Tips Pemain Baru",
    "newPlayerTips.close": "Tutup",
    "export.json": "Ekspor {char.name} sebagai JSON",
    "delete.confirm": "Apakah Anda yakin ingin menghapus {char.name}? Tindakan ini tidak bisa dibatalkan.",
    "import.pdfError": "PDF ini tidak berisi data karakter DND Wizard.",
    "import.jsonError": "Gagal mengimpor JSON karakter.",
    "import.success": 'Berhasil mengimpor "{name}".',
    "noData.characters": "Belum ada karakter. Buat karakter pertama Anda!",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("dnd-language") as Language | null;
    if (saved === "en" || saved === "id") {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("dnd-language", lang);
  }, []);

  const t = useCallback(
    (key: string, fallback?: string) => {
      const dict = translations[language];
      if (dict && dict[key]) return dict[key];
      const enDict = translations.en;
      if (enDict && enDict[key]) return enDict[key];
      return fallback || key;
    },
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
