"use client";

import {
  HumanIcon as Human,
  ElfIcon as Elf,
  DwarfIcon as Dwarf,
  PersonIcon as Halfling,
  DragonHeadIcon as Dragonborn,
  GnomeIcon as Gnome,
  ElfIcon as HalfElf,
  GoblinIcon as HalfOrc,
  DevilMaskIcon as Tiefling,
  HumanIcon as VariantHuman,
  PersonIcon as Bugbear,
  PersonIcon as Changeling,
  PersonIcon as Dhampir,
  PersonIcon as Firbolg,
  PersonIcon as Githyanki,
  PersonIcon as Githzerai,
  GoblinIcon as Goblin,
  GoblinIcon as Hobgoblin,
  KenkuIcon as Kenku,
  LizardfolkIcon as Lizardfolk,
  GoblinIcon as Orc,
  PersonIcon as Reborn,
  PersonIcon as Shifter,
  PersonIcon as Tabaxi,
  PersonIcon as Triton,
  PersonIcon as Hexblood,
} from "@/components/icons";

export const RACE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  Dragonborn,
  Dwarf,
  Elf,
  "Eladrin (Elf)": Elf,
  Gnome,
  "Deep Gnome (Svirfneblin)": Gnome,
  "Half-Elf": HalfElf,
  Halfling,
  "Lightfoot Halfling": Halfling,
  "Stout Halfling": Halfling,
  "Ghostwise Halfling": Halfling,
  "Half-Orc": HalfOrc,
  Human,
  VariantHuman,
  Tiefling,
  Bugbear,
  Changeling,
  Dhampir,
  Firbolg,
  Githyanki,
  Githzerai,
  Goblin,
  Hobgoblin,
  Kenku,
  Lizardfolk,
  Orc,
  Reborn,
  Shifter,
  Tabaxi,
  Triton,
  Hexblood,
};
