#!/usr/bin/env python3
"""
Translate D&D 5e feature text from English to Indonesian.
Only translates description, summary, and flavorText fields.
Preserves D&D mechanical terms.
"""

import json
import re
from pathlib import Path

PROTECTED_TERMS = {
    "Action", "Bonus Action", "Reaction", "Concentration", "Ritual", "Cantrip",
    "Spell Slot", "Hit Points", "Armor Class", "Saving Throw", "Proficiency Bonus",
    "Advantage", "Disadvantage", "Critical Hit", "Initiative", "Speed", "Hit Dice",
    "Death Save", "Long Rest", "Short Rest", "Level Up", "Experience Points",
    "Subclass", "Archetype", "Circle", "Domain", "Oath", "Patron", "Tradition",
    "College", "Path", "Way", "Weapon", "Armor", "Shield", "Potion", "Scroll",
    "Wand", "Staff", "Rod", "Ring", "Amulet", "Cloak", "Boots", "Gloves",
    "Belt", "Helmet", "Gauntlets", "Copper", "Silver", "Electrum", "Gold", "Platinum",
    "Darkvision", "Fey Ancestry", "Trance", "Relentless Endurance", "Savage Attacks",
    "Dwarven Resilience", "Dwarven Combat Training", "Tool Proficiency", "Stonecutting",
    "Skill Versatility", "Keen Senses", "Fey Step", "Mask of the Wild",
    "Elf Weapon Training", "Extra Language", "Gnome Cunning", "Artificer's Lore",
    "Tinker", "Speed", "Size", "Languages", "Barbarian", "Bard", "Cleric", "Druid",
    "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard",
    "Artificer", "Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Halfling",
    "Half-Orc", "Human", "Tiefling", "Aarakocra", "Genasi", "Goliath", "Kenku",
    "Tabaxi", "Triton", "Bugbear", "Goblin", "Hobgoblin", "Kobold", "Orc",
    "Yuan-ti Pureblood", "Feral Tiefling", "Aasimar", "Firbolg", "Kalashtar",
    "Shifter", "Warforged", "Changeling", "Eladrin", "Sea Elf", "Shadar-kai",
    "High Elf", "Wood Elf", "Dark Elf", "Drow", "Hill Dwarf", "Mountain Dwarf",
    "Lightfoot Halfling", "Stout Halfling", "Rock Gnome", "Forest Gnome",
    "Acid", "Bludgeoning", "Cold", "Fire", "Force", "Lightning", "Necrotic",
    "Piercing", "Poison", "Psychic", "Radiant", "Slashing", "Thunder",
    "Abjuration", "Conjuration", "Divination", "Enchantment", "Evocation",
    "Illusion", "Necromancy", "Transmutation", "Blinded", "Charmed", "Deafened",
    "Frightened", "Grappled", "Incapacitated", "Invisible", "Paralyzed",
    "Petrified", "Poisoned", "Prone", "Restrained", "Stunned", "Unconscious",
    "Exhaustion", "Strength", "Dexterity", "Constitution", "Intelligence",
    "Wisdom", "Charisma", "Acrobatics", "Animal Handling", "Arcana", "Athletics",
    "Deception", "History", "Insight", "Intimidation", "Investigation", "Medicine",
    "Nature", "Perception", "Performance", "Persuasion", "Religion",
    "Sleight of Hand", "Stealth", "Survival", "Lawful Good", "Neutral Good",
    "Chaotic Good", "Lawful Neutral", "True Neutral", "Chaotic Neutral",
    "Lawful Evil", "Neutral Evil", "Chaotic Evil", "Melee", "Ranged", "Touch",
    "Self", "Area", "Sphere", "Cube", "Cone", "Line", "Cylinder",
    "Instantaneous", "Round", "Minute", "Hour", "Day", "Until Dispelled",
    "Until Dispelled or Triggered", "Verbal", "Somatic", "Material",
    "Constitution Save", "Dexterity Save", "Wisdom Save", "Strength Save",
    "Intelligence Save", "Charisma Save", "Melee Spell Attack", "Ranged Spell Attack",
    "Higher Level", "Upcast", "At Higher Levels", "PHB", "XGE", "TCE", "MTF",
    "SCAG", "VGM", "MToF", "Tasha's", "Xanathar", "Mordenkainen",
}

# Common translation mappings
TRANSLATIONS = {
    "you can": "kamu dapat",
    "you can see": "kamu bisa melihat",
    "you have": "kamu memiliki",
    "you gain": "kamu mendapatkan",
    "you are": "kamu adalah",
    "when you": "ketika kamu",
    "whenever you": "setiap kali kamu",
    "if you": "jika kamu",
    "you can use": "kamu dapat menggunakan",
    "you can't": "kamu tidak bisa",
    "you cannot": "kamu tidak dapat",
    "you must": "kamu harus",
    "you may": "kamu bisa",
    "you can cast": "kamu dapat menyalurkan",
    "you regain": "kamu memulihkan kembali",
    "you can expend": "kamu dapat menghabiskan",
    "you can spend": "kamu dapat menghabiskan",
    "you can make": "kamu dapat membuat",
    "you can perform": "kamu dapat melakukan",
    "you can add": "kamu dapat menambahkan",
    "you can choose": "kamu dapat memilih",
    "you can select": "kamu dapat memilih",
    "you can apply": "kamu dapat menerapkan",
    "you can roll": "kamu dapat melempar",
    "you can ignore": "kamu dapat mengabaikan",
    "you can treat": "kamu dapat memperlakukan",
    "you can count": "kamu dapat menghitung",
    "you can speak": "kamu dapat berbicara",
    "you can read": "kamu dapat membaca",
    "you can write": "kamu dapat menulis",
    "you can understand": "kamu dapat memahami",
    "you can move": "kamu dapat bergerak",
    "you can take": "kamu dapat mengambil",
    "you can use an action": "kamu dapat menggunakan aksi",
    "you can use a bonus action": "kamu dapat menggunakan aksi bonus",
    "you can use your reaction": "kamu dapat menggunakan reaksimu",
    "you can use your action": "kamu dapat menggunakan aksimu",
    "you can use your bonus action": "kamu dapat menggunakan aksi bonusmu",
    "you can use your movement": "kamu dapat menggunakan gerakanmu",
    "you can't use": "kamu tidak bisa menggunakan",
    "you can't be": "kamu tidak bisa",
    "you can't see": "kamu tidak bisa melihat",
    "you can't move": "kamu tidak bisa bergerak",
    "you can't speak": "kamu tidak bisa berbicara",
    "you can't cast spells": "kamu tidak bisa menyalurkan sihir",
    "you can add your": "kamu dapat menambahkan",
    "you can add it to": "kamu dapat menambahkannya ke",
    "you can add this spell to": "kamu dapat menambahkan sihir ini ke",
    "you can add the spell to": "kamu dapat menambahkan sihir ke",
    "you can cast it": "kamu dapat menyalurkannya",
    "you can cast it again": "kamu dapat menyalurkannya lagi",
    "you can cast the spell": "kamu dapat menyalurkan sihir",
    "you can cast this spell": "kamu dapat menyalurkan sihir ini",
    "you can cast a spell": "kamu dapat menyalurkan sihir",
    "you can cast it without": "kamu dapat menyalurkannya tanpa",
    "you can cast it without expending": "kamu dapat menyalurkannya tanpa menghabiskan",
    "you can cast it without using": "kamu dapat menyalurkannya tanpa menggunakan",
    "you can cast it without spending": "kamu dapat menyalurkannya tanpa menghabiskan",
    "you can cast it again after": "kamu dapat menyalurkannya lagi setelah",
    "you can cast it again once": "kamu dapat menyalurkannya lagi sekali",
    "you can cast it again when": "kamu dapat menyalurkannya lagi ketika",
    "you can cast it again after you finish": "kamu dapat menyalurkannya lagi setelah kamu menyelesaikan",
    "you can cast it again after a short rest": "kamu dapat menyalurkannya lagi setelah istirahat singkat",
    "you can cast it again after a long rest": "kamu dapat menyalurkannya lagi setelah istirahat panjang",
    "you can cast it again when you finish": "kamu dapat menyalurkannya lagi ketika kamu menyelesaikan",
    "you can cast it again when you finish a short rest": "kamu dapat menyalurkannya lagi ketika kamu menyelesaikan istirahat singkat",
    "you can cast it again when you finish a long rest": "kamu dapat menyalurkannya lagi ketika kamu menyelesaikan istirahat panjang",
    "you can cast it again after you finish a short or long rest": "kamu dapat menyalurkannya lagi setelah kamu menyelesaikan istirahat singkat atau panjang",
    "you can cast the spell again after": "kamu dapat menyalurkan sihir lagi setelah",
    "you can cast the spell again once": "kamu dapat menyalurkan sihir lagi sekali",
    "you can cast the spell again when": "kamu dapat menyalurkan sihir lagi ketika",
    "you can cast the spell again after you finish": "kamu dapat menyalurkan sihir lagi setelah kamu menyelesaikan",
    "you can cast the spell again after a short rest": "kamu dapat menyalurkan sihir lagi setelah istirahat singkat",
    "you can cast the spell again after a long rest": "kamu dapat menyalurkan sihir lagi setelah istirahat panjang",
    "you can cast the spell again when you finish": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan",
    "you can cast the spell again when you finish a short rest": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan istirahat singkat",
    "you can cast the spell again when you finish a long rest": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan istirahat panjang",
    "you can cast the spell again after you finish a short or long rest": "kamu dapat menyalurkan sihir lagi setelah kamu menyelesaikan istirahat singkat atau panjang",
    "you can cast this spell again after": "kamu dapat menyalurkan sihir ini lagi setelah",
    "you can cast this spell again once": "kamu dapat menyalurkan sihir ini lagi sekali",
    "you can cast this spell again when": "kamu dapat menyalurkan sihir ini lagi ketika",
    "you can cast this spell again after you finish": "kamu dapat menyalurkan sihir ini lagi setelah kamu menyelesaikan",
    "you can cast this spell again after a short rest": "kamu dapat menyalurkan sihir ini lagi setelah istirahat singkat",
    "you can cast this spell again after a long rest": "kamu dapat menyalurkan sihir ini lagi setelah istirahat panjang",
    "you can cast this spell again when you finish": "kamu dapat menyalurkan sihir ini lagi ketika kamu menyelesaikan",
    "you can cast this spell again when you finish a short rest": "kamu dapat menyalurkan sihir ini lagi ketika kamu menyelesaikan istirahat singkat",
    "you can cast this spell again when you finish a long rest": "kamu dapat menyalurkan sihir ini lagi ketika kamu menyelesaikan istirahat panjang",
    "you can cast this spell again after you finish a short or long rest": "kamu dapat menyalurkan sihir ini lagi setelah kamu menyelesaikan istirahat singkat atau panjang",
    "you can cast a spell again after": "kamu dapat menyalurkan sihir lagi setelah",
    "you can cast a spell again once": "kamu dapat menyalurkan sihir lagi sekali",
    "you can cast a spell again when": "kamu dapat menyalurkan sihir lagi ketika",
    "you can cast a spell again after you finish": "kamu dapat menyalurkan sihir lagi setelah kamu menyelesaikan",
    "you can cast a spell again after a short rest": "kamu dapat menyalurkan sihir lagi setelah istirahat singkat",
    "you can cast a spell again after a long rest": "kamu dapat menyalurkan sihir lagi setelah istirahat panjang",
    "you can cast a spell again when you finish": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan",
    "you can cast a spell again when you finish a short rest": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan istirahat singkat",
    "you can cast a spell again when you finish a long rest": "kamu dapat menyalurkan sihir lagi ketika kamu menyelesaikan istirahat panjang",
    "you can cast a spell again after you finish a short or long rest": "kamu dapat menyalurkan sihir lagi setelah kamu menyelesaikan istirahat singkat atau panjang",
    "you can cast the spell once": "kamu dapat menyalurkan sihir sekali",
    "you can cast this spell once": "kamu dapat menyalurkan sihir ini sekali",
    "you can cast a spell once": "kamu dapat menyalurkan sihir sekali",
    "you can cast it once": "kamu dapat menyalurkannya sekali",
    "you can cast the spell without expending": "kamu dapat menyalurkan sihir tanpa menghabiskan",
    "you can cast this spell without expending": "kamu dapat menyalurkan sihir ini tanpa menghabiskan",
    "you can cast it without expending": "kamu dapat menyalurkannya tanpa menghabiskan",
    "a spell slot": "slot sihir",
    "spell slots": "slot sihir",
    "a spell": "sihir",
    "the spell": "sihir itu",
    "this spell": "sihir ini",
    "spell": "sihir",
    "spells": "sihir",
    "cantrip": "cantrip",
    "cantrips": "cantrip",
    "ritual": "ritual",
    "concentration": "konsentrasi",
    "a bonus action": "aksi bonus",
    "a reaction": "reaksi",
    "an action": "aksi",
    "your action": "aksimu",
    "your bonus action": "aksi bonusmu",
    "your reaction": "reaksimu",
    "your movement": "gerakanmu",
    "your turn": "giliranmu",
    "your next turn": "giliranmu selanjutnya",
    "your next turn begins": "giliranmu selanjutnya dimulai",
    "your next turn starts": "giliranmu selanjutnya dimulai",
    "your current turn": "giliranmu saat ini",
    "your turn ends": "giliranmu berakhir",
    "your turn begins": "giliranmu dimulai",
    "your turn starts": "giliranmu dimulai",
    "your speed": "kecepatanmu",
    "your walking speed": "kecepatan berjalanmu",
    "your movement speed": "kecepatan gerakanmu",
    "your AC": "AC-mu",
    "your hit points": "poin kesehatanmu",
    "your maximum hit points": "poin kesehatan maksimummu",
    "your hit point maximum": "maksimum poin kesehatanmu",
    "your proficiency bonus": "bonus keahlianmu",
    "your proficiency": "keahlianmu",
    "your ability scores": "nilai keampuanmu",
    "your ability score": "nilai keampuanmu",
    "your abilities": "keampuanmu",
    "your ability": "keampuanmu",
    "your strength": "kekuatanmu",
    "your dexterity": "ketrampilanganmu",
    "your constitution": "daya tahammu",
    "your intelligence": "kecerdasanmu",
    "your wisdom": "kebijaksanaanmu",
    "your charisma": "karismamu",
    "your saving throws": "saving throwmu",
    "your saving throw": "saving throwmu",
    "your skill": "ketrampilanmu",
    "your skills": "ketrampilanmu",
    "your skill proficiencies": "keahlian ketrampilanmu",
    "your tool": "alatmu",
    "your tools": "alatmu",
    "your weapon": "senjatamu",
    "your weapons": "senjatamu",
    "your armor": "armormu",
    "your equipment": "peralatanmu",
    "your inventory": "inventorimu",
    "your class features": "fitur kelasmu",
    "your class feature": "fitur kelasmu",
    "your racial traits": "sifat rasmu",
    "your racial trait": "sifat rasmu",
    "your background feature": "fitur latar belakangmu",
    "your background features": "fitur latar belakangmu",
    "your background": "latar belakangmu",
    "your character": "karaktermu",
    "your character's": "karaktermu",
    "your character level": "tingkat karaktermu",
    "your character sheet": "lembar karaktermu",
    "your hit point": "poin kesehatanmu",
    "your hit points maximum": "maksimum poin kesehatanmu",
    "your hit points are reduced": "poin kesehatanmu berkurang",
    "your hit points are reduced to 0": "poin kesehatanmu berkurang menjadi 0",
    "your hit points are reduced to 0, you fall": "poin kesehatanmu berkurang menjadi 0, kamu jatuh",
    "your hit points are reduced to 0, you fall unconscious": "poin kesehatanmu berkurang menjadi 0, kamu pingsan",
    "your hit points are reduced to 0, you fall unconscious and": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan",
    "your hit points are reduced to 0, you fall unconscious and you": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu",
    "your hit points are reduced to 0, you fall unconscious and you are": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu",
    "your hit points are reduced to 0, you fall unconscious and you are dying": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you start": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu mulai",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you start making": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu mulai membuat",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you start making death": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu mulai membuat kematian",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you start making death saving": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu mulai membuat saving throw kematian",
    "your hit points are reduced to 0, you fall unconscious and you are dying, and you start making death saving throws": "poin kesehatanmu berkurang menjadi 0, kamu pingsan dan kamu sekarat, dan kamu mulai membuat saving throw kematian",
    "a short rest": "istirahat singkat",
    "a long rest": "istirahat panjang",
    "a short or long rest": "istirahat singkat atau panjang",
    "during a short rest": "selama istirahat singkat",
    "during a long rest": "selama istirahat panjang",
    "after a short rest": "setelah istirahat singkat",
    "after a long rest": "setelah istirahat panjang",
    "after a short or long rest": "setelah istirahat singkat atau panjang",
    "finish a short rest": "menyelesaikan istirahat singkat",
    "finish a long rest": "menyelesaikan istirahat panjang",
    "finish a short or long rest": "menyelesaikan istirahat singkat atau panjang",
    "complete a short rest": "menyelesaikan istirahat singkat",
    "complete a long rest": "menyelesaikan istirahat panjang",
    "complete a short or long rest": "menyelesaikan istirahat singkat atau panjang",
    "a creature": "makhluk",
    "a creature within": "makhluk dalam",
    "a creature within X feet": "makhluk dalam X kaki",
    "a creature within range": "makhluk dalam jangkauan",
    "a creature of your choice": "makhluk pilihanmu",
    "a creature you can see": "makhluk yang kamu lihat",
    "a creature you can see within": "makhluk yang kamu lihat dalam",
    "a creature you can see within range": "makhluk yang kamu lihat dalam jangkauan",
    "one creature": "satu makhluk",
    "one creature of your choice": "satu makhluk pilihanmu",
    "one creature you can see": "satu makhluk yang kamu lihat",
    "each creature": "setiap makhluk",
    "each creature in": "setiap makhluk di",
    "each creature in the area": "setiap makhluk di area",
    "each creature in the area must": "setiap makhluk di area harus",
    "each creature in the area must make": "setiap makhluk di area harus membuat",
    "each creature in the area must make a": "setiap makhluk di area harus membuat",
    "each creature in the area must make a saving": "setiap makhluk di area harus membuat saving throw",
    "each creature in the area must make a saving throw": "setiap makhluk di area harus membuat saving throw",
    "each creature of your choice": "setiap makhluk pilihanmu",
    "each creature you can see": "setiap makhluk yang kamu lihat",
    "up to": "hingga",
    "up to X creatures": "hingga X makhluk",
    "up to three creatures": "hingga tiga makhluk",
    "up to two creatures": "hingga dua makhluk",
    "up to four creatures": "hingga empat makhluk",
    "hit points": "poin kesehatan",
    "hit point": "poin kesehatan",
    "temporary hit points": "poin kesehatan sementara",
    "maximum hit points": "maksimum poin kesehatan",
    "damage": "kerusakan",
    "damage dice": "dadu kerusakan",
    "damage type": "tipe kerusakan",
    "healing": "penyembuhan",
    "heal": "menyembuhkan",
    "heals": "menyembuhkan",
    "healed": "disembuhkan",
    "restores": "memulihkan",
    "restore": "memulihkan",
    "restored": "dipulihkan",
    "regains": "memulihkan kembali",
    "regain": "memulihkan kembali",
    "regained": "dipulihkan kembali",
    "gain": "mendapatkan",
    "gains": "mendapatkan",
    "gained": "didapatkan",
    "gain advantage": "mendapatkan keuntungan",
    "gain disadvantage": "mendapatkan kerugian",
    "gain proficiency": "mendapatkan keahlian",
    "gain expertise": "mendapatkan keahlian ahli",
    "gain a proficiency": "mendapatkan keahlian",
    "gain advantage on": "mendapatkan keuntungan pada",
    "gain disadvantage on": "mendapatkan kerugian pada",
    "gain proficiency in": "mendapatkan keahlian dalam",
    "gain advantage on saving throws": "mendapatkan keuntungan pada saving throw",
    "gain advantage on ability checks": "mendapatkan keuntungan pada ability check",
    "gain advantage on attack rolls": "mendapatkan keuntungan pada serangan",
    "you have advantage": "kamu memiliki keuntungan",
    "you have advantage on": "kamu memiliki keuntungan pada",
    "you have advantage on saving throws": "kamu memiliki keuntungan pada saving throw",
    "you have advantage on ability checks": "kamu memiliki keuntungan pada ability check",
    "you have advantage on attack rolls": "kamu memiliki keuntungan pada serangan",
    "you have disadvantage": "kamu memiliki kerugian",
    "you have disadvantage on": "kamu memiliki kerugian pada",
    "you are proficient": "kamu ahli",
    "you are proficient with": "kamu ahli dengan",
    "you are not proficient": "kamu tidak ahli",
    "you are not proficient with": "kamu tidak ahli dengan",
    "you become proficient": "kamu menjadi ahli",
    "you are immune": "kamu kebal",
    "you are immune to": "kamu kebal terhadap",
    "you are resistant": "kamu tahan",
    "you are resistant to": "kamu tahan terhadap",
    "you have resistance": "kamu memiliki ketahanan",
    "you have resistance to": "kamu memiliki ketahanan terhadap",
    "you have immunity": "kamu memiliki kekebalan",
    "you have immunity to": "kamu memiliki kekebalan terhadap",
    "you are vulnerable": "kamu rentan",
    "you are vulnerable to": "kamu rentan terhadap",
    "you are considered": "kamu dianggap",
    "you are considered to be": "kamu dianggap sebagai",
    "you are considered proficient": "kamu dianggap ahli",
    "you are considered proficient with": "kamu dianggap ahli dengan",
    "you are considered proficient in": "kamu dianggap ahli dalam",
    "you are proficient with": "kamu ahli dengan",
    "you are proficient in": "kamu ahli dalam",
    "you are proficient with all": "kamu ahli dengan semua",
    "you are proficient with all simple": "kamu ahli dengan semua sederhana",
    "you are proficient with all simple weapons": "kamu ahli dengan semua senjata sederhana",
    "you are proficient with all martial": "kamu ahli dengan semua tempur",
    "you are proficient with all martial weapons": "kamu ahli dengan semua senjata tempur",
    "you are proficient with light armor": "kamu ahli dengan armor ringan",
    "you are proficient with medium armor": "kamu ahli dengan armor medium",
    "you are proficient with heavy armor": "kamu ahli dengan armor berat",
    "you are proficient with shields": "kamu ahli dengan perisai",
    "you are proficient with simple weapons": "kamu ahli dengan senjata sederhana",
    "you are proficient with martial weapons": "kamu ahli dengan senjata tempur",
    "you are proficient with one type of": "kamu ahli dengan satu jenis",
    "you are proficient with one type of artisan's tools": "kamu ahli dengan satu jenis alat artisan",
    "you are proficient with one type of gaming set": "kamu ahli dengan satu jenis set permainan",
    "you are proficient with one type of musical instrument": "kamu ahli dengan satu jenis instrumen musik",
    "you are proficient with one type of tool": "kamu ahli dengan satu jenis alat",
    "you gain proficiency with": "kamu mendapatkan keahlian dengan",
    "you gain proficiency in": "kamu mendapatkan keahlian dalam",
    "you gain proficiency with one type of": "kamu mendapatkan keahlian dengan satu jenis",
    "you gain proficiency with one type of artisan's tools": "kamu mendapatkan keahlian dengan satu jenis alat artisan",
    "you gain proficiency with one type of gaming set": "kamu mendapatkan keahlian dengan satu jenis set permainan",
    "you gain proficiency with one type of musical instrument": "kamu mendapatkan keahlian dengan satu jenis instrumen musik",
    "you gain proficiency with one type of tool": "kamu mendapatkan keahlian dengan satu jenis alat",
    "you gain proficiency with your choice of one type of": "kamu mendapatkan keahlian dengan pilihan satu jenis",
    "you gain proficiency with your choice of one type of artisan's tools": "kamu mendapatkan keahlian dengan pilihan satu jenis alat artisan",
    "you gain proficiency with your choice of one type of gaming set": "kamu mendapatkan keahlian dengan pilihan satu jenis set permainan",
    "you gain proficiency with your choice of one type of musical instrument": "kamu mendapatkan keahlian dengan pilihan satu jenis instrumen musik",
    "you gain proficiency with your choice of one type of tool": "kamu mendapatkan keahlian dengan pilihan satu jenis alat",
    "you gain proficiency with one additional type of": "kamu mendapatkan keahlian dengan satu jenis tambahan",
    "you gain proficiency with one additional type of artisan's tools": "kamu mendapatkan keahlian dengan satu jenis tambahan alat artisan",
    "you gain proficiency with one additional type of gaming set": "kamu mendapatkan keahlian dengan satu jenis tambahan set permainan",
    "you gain proficiency with one additional type of musical instrument": "kamu mendapatkan keahlian dengan satu jenis tambahan instrumen musik",
    "you gain proficiency with one additional type of tool": "kamu mendapatkan keahlian dengan satu jenis tambahan alat",
    "you gain proficiency with two types of": "kamu mendapatkan keahlian dengan dua jenis",
    "you gain proficiency with all tools": "kamu mendapatkan keahlian dengan semua alat",
    "you gain proficiency with all weapons": "kamu mendapatkan keahlian dengan semua senjata",
    "you gain proficiency with all armor": "kamu mendapatkan keahlian dengan semua armor",
    "you gain proficiency with all simple weapons": "kamu mendapatkan keahlian dengan semua senjata sederhana",
    "you gain proficiency with all martial weapons": "kamu mendapatkan keahlian dengan semua senjata tempur",
    "you gain proficiency with light armor": "kamu mendapatkan keahlian dengan armor ringan",
    "you gain proficiency with medium armor": "kamu mendapatkan keahlian dengan armor medium",
    "you gain proficiency with heavy armor": "kamu mendapatkan keahlian dengan armor berat",
    "you gain proficiency with shields": "kamu mendapatkan keahlian dengan perisai",
    "you gain proficiency in saving throws": "kamu mendapatkan keahlian dalam saving throw",
    "you gain proficiency in ability checks": "kamu mendapatkan keahlian dalam ability check",
    "you gain proficiency in skills": "kamu mendapatkan keahlian dalam ketrampilan",
    "you gain proficiency in all saving throws": "kamu mendapatkan keahlian dalam semua saving throw",
    "you gain proficiency in all ability checks": "kamu mendapatkan keahlian dalam semua ability check",
    "you gain proficiency in all skills": "kamu mendapatkan keahlian dalam semua ketrampilan",
    "you gain proficiency in two skills": "kamu mendapatkan keahlian dalam dua ketrampilan",
    "you gain proficiency in three skills": "kamu mendapatkan keahlian dalam tiga ketrampilan",
    "you gain proficiency in four skills": "kamu mendapatkan keahlian dalam empat ketrampilan",
    "you gain proficiency in X skills": "kamu mendapatkan keahlian dalam X ketrampilan",
    "you gain proficiency in X skills of your choice": "kamu mendapatkan keahlian dalam X ketrampilan pilihanmu",
    "you gain proficiency in two skills of your choice": "kamu mendapatkan keahlian dalam dua ketrampilan pilihanmu",
    "you gain proficiency in three skills of your choice": "kamu mendapatkan keahlian dalam tiga ketrampilan pilihanmu",
    "you gain proficiency in four skills of your choice": "kamu mendapatkan keahlian dalam empat ketrampilan pilihanmu",
    "you gain proficiency in X skills of your choice from": "kamu mendapatkan keahlian dalam X ketrampilan pilihanmu dari",
    "you gain proficiency in two skills of your choice from": "kamu mendapatkan keahlian dalam dua ketrampilan pilihanmu dari",
    "you gain proficiency in three skills of your choice from": "kamu mendapatkan keahlian dalam tiga ketrampilan pilihanmu dari",
    "you gain proficiency in four skills of your choice from": "kamu mendapatkan keahlian dalam empat ketrampilan pilihanmu dari",
    "you gain proficiency in all skills": "kamu mendapatkan keahlian dalam semua ketrampilan",
    "you gain proficiency in one skill": "kamu mendapatkan keahlian dalam satu ketrampilan",
    "you gain proficiency in one skill of your choice": "kamu mendapatkan keahlian dalam satu ketrampilan pilihanmu",
    "you gain proficiency in one skill of your choice from": "kamu mendapatkan keahlian dalam satu ketrampilan pilihanmu dari",
    "you gain proficiency in a skill": "kamu mendapatkan keahlian dalam sebuah ketrampilan",
    "you gain proficiency in a skill of your choice": "kamu mendapatkan keahlian dalam sebuah ketrampilan pilihanmu",
    "you gain proficiency in a skill of your choice from": "kamu mendapatkan keahlian dalam sebuah ketrampilan pilihanmu dari",
    "you gain proficiency in the following skills": "kamu mendapatkan keahlian dalam ketrampilan berikut",
    "you gain proficiency in the following skill": "kamu mendapatkan keahlian dalam ketrampilan berikut",
    "you gain proficiency in the skill": "kamu mendapatkan keahlian dalam ketrampilan",
    "you gain proficiency in the skill of your choice": "kamu mendapatkan keahlian dalam ketrampilan pilihanmu",
    "you gain proficiency in the skill of your choice from": "kamu mendapatkan keahlian dalam ketrampilan pilihanmu dari",
    "you gain proficiency in two of the following skills": "kamu mendapatkan keahlian dalam dua dari ketrampilan berikut",
    "you gain proficiency in three of the following skills": "kamu mendapatkan keahlian dalam tiga dari ketrampilan berikut",
    "you gain proficiency in four of the following skills": "kamu mendapatkan keahlian dalam empat dari ketrampilan berikut",
    "you gain proficiency in X of the following skills": "kamu mendapatkan keahlian dalam X dari ketrampilan berikut",
    "you gain proficiency in two skills from": "kamu mendapatkan keahlian dalam dua ketrampilan dari",
    "you gain proficiency in three skills from": "kamu mendapatkan keahlian dalam tiga ketrampilan dari",
    "you gain proficiency in four skills from": "kamu mendapatkan keahlian dalam empat ketrampilan dari",
    "you gain proficiency in X skills from": "kamu mendapatkan keahlian dalam X ketrampilan dari",
    "you gain proficiency in two skills of your choice from the following list": "kamu mendapatkan keahlian dalam dua ketrampilan pilihanmu dari daftar berikut",
    "you gain proficiency in three skills of your choice from the following list": "kamu mendapatkan keahlian dalam tiga ketrampilan pilihanmu dari daftar berikut",
    "you gain proficiency in four skills of your choice from the following list": "kamu mendapatkan keahlian dalam empat ketrampilan pilihanmu dari daftar berikut",
    "you gain proficiency in X skills of your choice from the following list": "kamu mendapatkan keahlian dalam X ketrampilan pilihanmu dari daftar berikut",
    "you can add your proficiency bonus": "kamu dapat menambahkan bonus keahlianmu",
    "you can add your proficiency bonus to": "kamu dapat menambahkan bonus keahlianmu ke",
    "you can add your proficiency bonus to the following": "kamu dapat menambahkan bonus keahlianmu ke berikut",
    "you can add your proficiency bonus to the following checks": "kamu dapat menambahkan bonus keahlianmu ke check berikut",
    "you can add your proficiency bonus to the following ability checks": "kamu dapat menambahkan bonus keahlianmu ke ability check berikut",
    "you can add your proficiency bonus to the following saving throws": "kamu dapat menambahkan bonus keahlianmu ke saving throw berikut",
    "you can add your proficiency bonus to the following skills": "kamu dapat menambahkan bonus keahlianmu ke ketrampilan berikut",
    "you can add your proficiency bonus to any": "kamu dapat menambahkan bonus keahlianmu ke",
    "you can add your proficiency bonus to any ability check": "kamu dapat menambahkan bonus keahlianmu ke ability check",
    "you can add your proficiency bonus to any saving throw": "kamu dapat menambahkan bonus keahlianmu ke saving throw",
    "you can add your proficiency bonus to any check": "kamu dapat menambahkan bonus keahlianmu ke check",
    "a short rest": "istirahat singkat",
    "a long rest": "istirahat panjang",
    "a short or long rest": "istirahat singkat atau panjang",
    "hit points": "poin kesehatan",
    "hit point": "poin kesehatan",
    "temporary hit points": "poin kesehatan sementara",
    "damage": "kerusakan",
    "healing": "penyembuhan",
    "advantage": "keuntungan",
    "disadvantage": "kerugian",
    "proficiency": "keahlian",
    "you have advantage on all saving throws": "kamu memiliki keuntungan pada semua saving throw",
    "you have advantage on all ability checks": "kamu memiliki keuntungan pada semua ability check",
    "you have advantage on all attack rolls": "kamu memiliki keuntungan pada semua serangan",
    "you have advantage on saving throws against": "kamu memiliki keuntungan pada saving throw melawan",
    "you have advantage on ability checks against": "kamu memiliki keuntungan pada ability check melawan",
    "you have advantage on attack rolls against": "kamu memiliki keuntungan pada serangan melawan",
    "you have disadvantage on saving throws": "kamu memiliki kerugian pada saving throw",
    "you have disadvantage on ability checks": "kamu memiliki kerugian pada ability check",
    "you have disadvantage on attack rolls": "kamu memiliki kerugian pada serangan",
    "you are proficient with all simple and martial weapons": "kamu ahli dengan semua senjata sederhana dan tempur",
    "you are proficient with all simple and martial weapons, and": "kamu ahli dengan semua senjata sederhana dan tempur, dan",
    "you are proficient with all simple and martial weapons, and all armor": "kamu ahli dengan semua senjata sederhana dan tempur, dan semua armor",
    "you are proficient with all simple and martial weapons, and all armor and shields": "kamu ahli dengan semua senjata sederhana dan tempur, dan semua armor dan perisai",
    "you can do so": "kamu bisa melakukannya",
    "you can do so a number of times": "kamu bisa melakukannya sebanyak",
    "you can do so a number of times equal to": "kamu bisa melakukannya sebanyak",
    "you can do so without expending": "kamu bisa melakukannya tanpa menghabiskan",
    "you can do so again after": "kamu bisa melakukannya lagi setelah",
    "you can do so again after a short rest": "kamu bisa melakukannya lagi setelah istirahat singkat",
    "you can do so again after a long rest": "kamu bisa melakukannya lagi setelah istirahat panjang",
    "you can do so again after a short or long rest": "kamu bisa melakukannya lagi setelah istirahat singkat atau panjang",
    "you can do so once": "kamu bisa melakukannya sekali",
    "you can do so once per": "kamu bisa melakukannya sekali per",
    "you can do so once per short rest": "kamu bisa melakukannya sekali per istirahat singkat",
    "you can do so once per long rest": "kamu bisa melakukannya sekali per istirahat panjang",
    "when you finish": "ketika kamu menyelesaikan",
    "when you finish a short rest": "ketika kamu menyelesaikan istirahat singkat",
    "when you finish a long rest": "ketika kamu menyelesaikan istirahat panjang",
    "when you finish a short or long rest": "ketika kamu menyelesaikan istirahat singkat atau panjang",
}


def protect_terms(text):
    """Replace protected terms with placeholders."""
    sorted_terms = sorted(PROTECTED_TERMS, key=len, reverse=True)
    placeholders = {}
    for i, term in enumerate(sorted_terms):
        placeholder = f"__PROTECTED_{i}__"
        placeholders[placeholder] = term
        text = re.sub(r'\b' + re.escape(term) + r'\b', placeholder, text)
    return text, placeholders


def unprotect_terms(text, placeholders):
    """Restore protected terms."""
    for placeholder, term in placeholders.items():
        text = text.replace(placeholder, term)
    return text


def translate_text(text):
    """Translate English text to Indonesian."""
    if not text or not isinstance(text, str):
        return text

    # Protect D&D terms
    protected, placeholders = protect_terms(text)

    # Apply translations (longest phrases first to avoid partial matches)
    sorted_keys = sorted(TRANSLATIONS.keys(), key=len, reverse=True)
    result = protected
    for eng in sorted_keys:
        ind = TRANSLATIONS[eng]
        result = re.sub(r'\b' + re.escape(eng) + r'\b', ind, result)

    # Unprotect terms
    result = unprotect_terms(result, placeholders)
    return result


def translate_value(value):
    """Translate a string value."""
    if not isinstance(value, str) or not value.strip():
        return value
    return translate_text(value)


def walk_and_translate(obj, fields_to_translate):
    """Walk through JSON object and translate specified fields."""
    if isinstance(obj, dict):
        result = {}
        for key, value in obj.items():
            if key in fields_to_translate and isinstance(value, str) and value.strip():
                result[key] = translate_value(value)
            else:
                result[key] = walk_and_translate(value, fields_to_translate)
        return result
    elif isinstance(obj, list):
        return [walk_and_translate(item, fields_to_translate) for item in obj]
    return obj


def main():
    fields = ["description", "fullDescription", "flavorText", "summary", "effectSummary"]

    files = [
        "src/data/id/2014_classes.json",
        "src/data/id/2014_subclasses.json",
        "src/data/id/2014_races.json",
    ]

    for filepath in files:
        path = Path(filepath)
        if not path.exists():
            print(f"Skip missing: {filepath}")
            continue

        data = json.loads(path.read_text())
        translated = walk_and_translate(data, fields)
        out = json.dumps(translated, ensure_ascii=False, indent=2) + "\n"
        path.write_text(out)
        print(f"Translated: {filepath}")


if __name__ == "__main__":
    main()
