import fs from "fs";
import path from "path";
import https from "https";
import http from "http";

const EN_DIR = path.join(process.cwd(), "src/data/en");
const ID_DIR = path.join(process.cwd(), "src/data/id");

const TRANSLATABLE_KEYS = new Set([
  "description",
  "fullDescription",
  "flavorText",
  "effectSummary",
]);

const PROTECTED_TERMS = [
  "Action",
  "Bonus Action",
  "Reaction",
  "Free Action",
  "Action Surge",
  "saving throw",
  "attack roll",
  "Advantage",
  "Disadvantage",
  "critical hit",
  "critical hit",
  "Hit Points",
  "HP",
  "AC",
  "Armor Class",
  "Initiative",
  "Concentration",
  "spell slot",
  "cantrip",
  "evocation",
  "V",
  "S",
  "M",
  "20-foot radius",
  "30 feet",
  "cone",
  "sphere",
  "line",
  "cube",
  "Charmed",
  "Prone",
  "Frightened",
  "Grappled",
  "Restrained",
  "Incapacitated",
  "Sneak Attack",
  "Rage",
  "Bardic Inspiration",
  "Darkvision",
  "bludgeoning",
  "piercing",
  "slashing",
  "fire",
  "necrotic",
  "radiant",
  "Strength",
  "Dexterity",
  "Constitution",
  "Intelligence",
  "Wisdom",
  "Charisma",
  "passive Perception",
  "Skill",
  "Proficiency",
  "Level",
  "Turn",
  "Round",
  "Range",
  "Duration",
  "School",
  "Damage",
  "Condition",
  "Effect",
  "Target",
  "Area",
  "Self",
  "Creature",
  "Point",
  "Sphere",
  "Cube",
  "Cone",
  "Line",
  "Cylinder",
  "Hemisphere",
  "Touch",
  "Special",
  "Melee",
  "Ranged",
  "Weapon",
  "Armor",
  "Shield",
  "Heavy",
  "Light",
  "Medium",
  "Finesse",
  "Two-Handed",
  "Versatile",
  "Thrown",
  "Ammunition",
  "Loading",
  "Reach",
  "Stealth",
  "Range",
  "normal",
  "long",
  "ft",
  "feet",
  "mile",
  "miles",
  "kilometer",
  "kilometers",
  "meter",
  "meters",
  "lb",
  "lbs",
  "pound",
  "pounds",
  "gp",
  "sp",
  "cp",
  "pp",
  "ep",
  "gold",
  "silver",
  "copper",
  "platinum",
  "electrum",
  "Rarity",
  "Common",
  "Uncommon",
  "Rare",
  "Very Rare",
  "Legendary",
  "Artifact",
  "Attunement",
  "Requires Attunement",
  "Cursed",
  "Sentient",
  "Intelligence",
  "Wisdom",
  "Charisma",
  "alignment",
  "Lawful",
  "Neutral",
  "Chaotic",
  "Good",
  "Evil",
  " proficiency",
  "bonus",
  "penalty",
  "modifier",
  "check",
  "save",
  "DC",
  "Difficulty Class",
  "Spellcasting",
  " Spellcasting",
  "Focus",
  "Component",
  "Material",
  "Verbal",
  "Somatic",
  "Ritual",
  "Duration",
  "Instantaneous",
  "Permanent",
  "Concentration",
  "up to",
  "level",
  "slot",
  "slots",
  "higher level",
  "at higher levels",
  "Using",
  "use",
  "uses",
  "recharge",
  "Charges",
  "Charge",
  "rest",
  "short rest",
  "long rest",
  "hit dice",
  "Hit Dice",
  "Death Saving Throw",
  "success",
  "failure",
  "stabilized",
  "dying",
  "dead",
  "exhaustion",
  "level of exhaustion",
  "Speed",
  "Fly",
  "Swim",
  "Climb",
  "Burrow",
  "Walk",
  "Vision",
  "Blind",
  "deafened",
  "paralyzed",
  "petrified",
  "poisoned",
  "stunned",
  "unconscious",
  "invisible",
  "detect",
  "sense",
  "resistance",
  "immune",
  "vulnerable",
  "advantage",
  "disadvantage",
  "proficiency bonus",
  "expertise",
  "Jack of All Trades",
  "Remarkable Athlete",
  "Reliable Talent",
  "Slippery Mind",
  "Keen Mind",
  "Lucky",
  "Alert",
  "Mobile",
  "Resilient",
  "Skilled",
  "Tavern Brawler",
  "Weapon Master",
  "Grappler",
  "Inspiring Leader",
  "Tavern Brawler",
  "Healer",
  "Medium Armor Master",
  "Heavily Armored",
  "Lightly Armored",
  "Martial Adept",
  "Metamagic Adept",
  "Fighting Initiate",
  "Strixhaven Mascot",
  "Fey Touched",
  "Shadow Touched",
  "Telekinetic",
  "Telepathic",
  "Artificer Initiate",
  "Crusher",
  "Piercer",
  "Slasher",
  "Flames of Phlegethos",
  "Gift of the Metallic Dragon",
  "Dungeon Delver",
  "Eldritch Adept",
  "Fey Wanderer",
  "Genie",
  "Giant",
  "Gloom Stalker",
  "Horizon Walker",
  "Monster Slayer",
  "Primeval Guardian",
  "Swarmkeeper",
  "Rune Knight",
  "Psi Warrior",
  "Aberrant Dragonmark",
  "Bard",
  "Cleric",
  "Druid",
  "Paladin",
  "Ranger",
  "Sorcerer",
  "Warlock",
  "Wizard",
  "Fighter",
  "Monk",
  "Rogue",
  "Barbarian",
  "Artificer",
  "Blood Hunter",
  "Artificer",
  "Alchemist",
  "Armorer",
  "Battle Smith",
  "Artillerist",
  "Dragon", // partial matches
  "Disciple",
  "Echo",
  "Ghost",
  "Gloom",
  "Horizon",
  "Hunter",
  "Lore",
  "Life",
  "Light",
  "Nature",
  "Tempest",
  "Trickery",
  "War",
  "Knowledge",
  "Arcana",
  "History",
  "Nature",
  "Religion",
  "Beast",
  "Wild",
  "Circle",
  "Dreams",
  "Spores",
  "Stars",
  "Shepherd",
  "Land",
  "Devotion",
  "Ancients",
  "Vengeance",
  "Oathbreaker",
  "Crown",
  "Glory",
  "Redemption",
  "Watchers",
  "Oath",
  "Beast",
  "Fey",
  "Fiend",
  "Undying",
  "Genie",
  "Great",
  "Old",
  "Hexblade",
  "Undead",
  "Undead",
  "Phantom",
  "Genie",
  "Fathomless",
  "Ghost",
  "Archfey",
  "Celestial",
  "Fiend",
  "Great",
  "Old",
  "Undying",
  "Hexblade",
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "Illusion",
  "Necromancy",
  "Transmutation",
  "Illusion",
  "Necromancy",
  "Transmutation",
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "School",
  "Tradition",
  "School of",
  "Lore",
  "War",
  "Sorcery",
  "Wild Magic",
  "Draconic",
  "Shadow",
  "Divine Soul",
  "Storm",
  "Phoenix",
  "Aberrant",
  "Clockwork",
  "Rune",
  "Bardic",
  "Inspiration",
  "Cutting Words",
  "Jack of All Trades",
  "Expertise",
  "Font of Inspiration",
  "Countercharm",
  "Magical Secrets",
  "Superior Inspiration",
  "Song of Rest",
  "Word of Radiance",
  "Vicious Mockery",
  "Friends",
  "Thunderclap",
  "Light",
  "Message",
  "Mage Hand",
  "Prestidigitation",
  "Minor Illusion",
  "Fire Bolt",
  "Ray of Frost",
  "Shocking Grasp",
  "Sword Burst",
  "Booming Blade",
  "Green-Flame Blade",
  "Lightning Lure",
  "Mind Sliver",
  "Sacred Flame",
  "Spare the Dying",
  "Thaumaturgy",
  "True Strike",
  "Control Flames",
  "Create Bonfire",
  "Druidcraft",
  "Flame Blade",
  "Frostbite",
  "Gust",
  "Infestation",
  "Magic Stone",
  "Mending",
  "Message",
  "Minor Illusion",
  "Mold Earth",
  "Poison Spray",
  "Prestidigitation",
  "Produce Flame",
  "Ray of Frost",
  "Resistance",
  "Shape Water",
  "Sword Burst",
  "Thunderclap",
  "Toll the Dead",
  "Thorn Whip",
  "Thunderwave",
  "Acid Splash",
  "Chill Touch",
  "Dancing Lights",
  "Fire Bolt",
  "Light",
  "Mage Hand",
  "Mending",
  "Message",
  "Minor Illusion",
  "Poison Spray",
  "Prestidigitation",
  "Ray of Frost",
  "Shocking Grasp",
  "Spare the Dying",
  "Sacred Flame",
  "Thaumaturgy",
  "Vicious Mockery",
  "Blade Ward",
  "Friends",
  "Light",
  "Message",
  "Mind Sliver",
  "Sword Burst",
  "Thunderclap",
  "Control Flames",
  "Create Bonfire",
  "Druidcraft",
  "Flame Blade",
  "Frostbite",
  "Gust",
  "Infestation",
  "Magic Stone",
  "Mold Earth",
  "Poison Spray",
  "Prestidigitation",
  "Produce Flame",
  "Ray of Frost",
  "Resistance",
  "Shape Water",
  "Thorn Whip",
  "Thunderwave",
  "Toll the Dead",
  "Word of Radiance",
  "Booming Blade",
  "Green-Flame Blade",
  "Lightning Lure",
  "Sword Burst",
  "Thunderclap",
  "Mind Sliver",
  "Sacred Flame",
  "Spare the Dying",
  "Thaumaturgy",
  "True Strike",
  "Vicious Mockery",
  "Acid Splash",
  "Chill Touch",
  "Dancing Lights",
  "Fire Bolt",
  "Light",
  "Mage Hand",
  "Mending",
  "Message",
  "Minor Illusion",
  "Poison Spray",
  "Prestidigitation",
  "Ray of Frost",
  "Shocking Grasp",
  "Spare the Dying",
  "Sacred Flame",
  "Thaumaturgy",
  "Vicious Mockery",
  "Blade Ward",
  "Friends",
  "Light",
  "Message",
  "Mind Sliver",
  "Sword Burst",
  "Thunderclap",
  "Control Flames",
  "Create Bonfire",
  "Druidcraft",
  "Flame Blade",
  "Frostbite",
  "Gust",
  "Infestation",
  "Magic Stone",
  "Mold Earth",
  "Poison Spray",
  "Prestidigitation",
  "Produce Flame",
  "Ray of Frost",
  "Resistance",
  "Shape Water",
  "Thorn Whip",
  "Thunderwave",
  "Toll the Dead",
  "Word of Radiance",
  "Booming Blade",
  "Green-Flame Blade",
  "Lightning Lure",
  "Sword Burst",
  "Thunderclap",
  "Mind Sliver",
  "Sacred Flame",
  "Spare the Dying",
  "Thaumaturgy",
  "True Strike",
  "Vicious Mockery",
  "Aberrant Mind",
  "Clockwork Soul",
  "Aberrant",
  "Clockwork",
  "Divine",
  "Draconic",
  "Shadow",
  "Storm",
  "Wild",
  "Fey",
  "Fiend",
  "Celestial",
  "Genie",
  "Undying",
  "Hexblade",
  "Undead",
  "Aberrant",
  "Great",
  "Old",
  "Ghost",
  "Fathomless",
  "Genie",
  "Aberrant",
  "Clockwork",
  "Lore",
  "War",
  "Illusion",
  "Necromancy",
  "Transmutation",
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "Rune",
  "Psi",
  "Wild",
  "Magic",
  "Psi",
  "Warrior",
  "Rune",
  "Knight",
  "Swarmkeeper",
  "Monster",
  "Slayer",
  "Horizon",
  "Gloom",
  "Stalker",
  "Fey",
  "Wanderer",
  "Giant",
  "Genie",
  "Fathomless",
  "Ghost",
  "Archfey",
  "Celestial",
  "Fiend",
  "Great",
  "Old",
  "Undying",
  "Hexblade",
  "Aberrant",
  "Clockwork",
  "Lore",
  "War",
  "Illusion",
  "Necromancy",
  "Transmutation",
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "Rune",
  "Psi",
  "Wild",
  "Magic",
  "Psi",
  "Warrior",
  "Rune",
  "Knight",
  "Swarmkeeper",
  "Monster",
  "Slayer",
  "Horizon",
  "Gloom",
  "Stalker",
  "Fey",
  "Wanderer",
  "Giant",
  "Genie",
  "Fathomless",
  "Ghost",
  "Archfey",
  "Celestial",
  "Fiend",
  "Great",
  "Old",
  "Undying",
  "Hexblade",
  "Aberrant",
  "Clockwork",
  "Lore",
  "War",
  "Illusion",
  "Necromancy",
  "Transmutation",
  "Abjuration",
  "Conjuration",
  "Divination",
  "Enchantment",
  "Evocation",
  "Rune",
  "Psi",
  "Wild",
  "Magic",
  "Psi",
  "Warrior",
  "Rune",
  "Knight",
  "Swarmkeeper",
  "Monster",
  "Slayer",
  "Horizon",
  "Gloom",
  "Stalker",
  "Fey",
  "Wanderer",
  "Giant",
  "Genie",
  "Fathomless",
  "Ghost",
  "Archfey",
  "Celestial",
  "Fiend",
  "Great",
  "Old",
  "Undying",
  "Hexblade",
]);

function buildProtectedRegex() {
  const escaped = PROTECTED_TERMS.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  return new RegExp(`\\b(${escaped.join("|")})\\b`, "gi");
}

const PROTECTED_REGEX = buildProtectedRegex();

function protectTerms(text: string): string {
  return text.replace(PROTECTED_REGEX, (match) => `__PROTECTED_${Buffer.from(match).toString("base64")}__`);
}

function restoreTerms(text: string): string {
  return text.replace(/__PROTECTED_([A-Za-z0-9+/=]+)__/g, (_, b64) => Buffer.from(b64, "base64").toString("utf8"));
}

async function translateText(text: string): Promise<string> {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.warn("OPENAI_API_KEY not set; returning original text.");
    return text;
  }

  const systemPrompt = `You are a D&D 5e localization expert translating flavor text and narrative descriptions from English to Bahasa Indonesia.

CRITICAL RULES:
1. ONLY translate narrative/descriptive text. Keep ALL official D&D 5e mechanical terms in English.
2. Never translate: spell names, class names, race names, subclass names, feature names, ability score names, condition names, damage types, action economy terms, distances/areas, dice notation, item names, proper nouns.
3. Mechanical terms to ALWAYS keep in English include (but are not limited to):
   - Ability Scores: Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma
   - Rolls/Mechanics: saving throw, attack roll, Advantage, Disadvantage, critical hit, passive Perception, ability check, skill check
   - Action Economy: Action, Bonus Action, Reaction, Free Action, Turn, Round
   - Combat: AC (Armor Class), Hit Points, temporary Hit Points, Initiative, Speed, range
   - Magic: Concentration, spell slot, cantrip, spell level, casting time, duration, components (V/S/M), school names (Evocation, etc.)
   - Distances/Areas: 20-foot radius, 30 feet, cone, sphere, line, cube, cylinder, hemisphere, feet, ft
   - Conditions: Charmed, Prone, Frightened, Grappled, Restrained, Incapacitated, Paralyzed, Petrified, Poisoned, Stunned, Unconscious, Invisible, Blinded, Deafened
   - Class Features: Sneak Attack, Rage, Bardic Inspiration, Darkvision, Action Surge, Ki Points, Sorcery Points, Channel Divinity, etc.
   - Damage Types: bludgeoning, piercing, slashing, fire, cold, lightning, thunder, poison, acid, psychic, necrotic, radiant, force
   - Other: proficiency, bonus, penalty, modifier, DC (Difficulty Class), attunement, rarity names, alignment names, hit dice, exhaustion levels
4. Use natural, fluent Bahasa Indonesia for the narrative parts.
5. Output ONLY the translated text. No explanations, no quotes, no markdown.`;

  const payload = JSON.stringify({
    model: "gpt-4o-mini",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: text },
    ],
    temperature: 0.2,
  });

  const url = new URL("https://api.openai.com/v1/chat/completions");

  const response = await new Promise<any>((resolve, reject) => {
    const req = https.request(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
    }, (res) => {
      let body = "";
      res.on("data", (chunk) => (body += chunk));
      res.on("end", () => {
        try {
          resolve(JSON.parse(body));
        } catch (e) {
          reject(new Error(`Failed to parse response: ${body}`));
        }
      });
    });
    req.on("error", reject);
    req.write(payload);
    req.end();
  });

  if (response.error) {
    throw new Error(`OpenAI API error: ${response.error.message}`);
  }

  const translated = response.choices?.[0]?.message?.content?.trim();
  if (!translated) {
    throw new Error("Empty translation response");
  }

  return translated;
}

async function translateValue(value: any): Promise<any> {
  if (typeof value === "string") {
    return translateText(value);
  }
  if (Array.isArray(value)) {
    return Promise.all(value.map(translateValue));
  }
  if (value && typeof value === "object") {
    const out: Record<string, any> = {};
    for (const [k, v] of Object.entries(value)) {
      out[k] = await translateValue(v);
    }
    return out;
  }
  return value;
}

async function processFile(filePath: string, outPath: string) {
  const raw = fs.readFileSync(filePath, "utf8");
  const data = JSON.parse(raw);

  const translated = await translateValue(data);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(translated, null, 2));
  console.log(`Translated: ${path.basename(filePath)} -> ${path.basename(outPath)}`);
}

async function main() {
  const files = fs.readdirSync(EN_DIR).filter((f) => f.endsWith(".json"));
  if (files.length === 0) {
    console.log("No JSON files found in src/data/en/");
    return;
  }

  console.log(`Found ${files.length} files to translate.`);
  console.log("WARNING: Translating all SRD data may use significant API credits.");
  console.log("Press Ctrl+C within 10 seconds to cancel...\n");

  await new Promise((resolve) => setTimeout(resolve, 10000));

  for (const file of files) {
    const srcPath = path.join(EN_DIR, file);
    const dstPath = path.join(ID_DIR, file);
    try {
      await processFile(srcPath, dstPath);
    } catch (err) {
      console.error(`Failed to translate ${file}:`, err);
    }
  }

  console.log("\nTranslation complete.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
